/**
 * capability-hub — 静态 DOM 契约与 bridge fallback
 */
const { describe, it } = require('node:test')
const assert = require('node:assert')
const fs = require('fs')
const path = require('path')

const root = path.join(__dirname, '..', 'src')
const html = fs.readFileSync(path.join(root, 'capability-hub.html'), 'utf8')
const js = fs.readFileSync(path.join(root, 'capability-hub.js'), 'utf8')
const css = fs.readFileSync(path.join(root, 'capability-hub.css'), 'utf8')

describe('capability hub static contract', () => {
  it('html shell includes tabs, search, grid, drawer, add dialog', () => {
    assert.ok(html.includes('id="hubSearch"'), 'search input')
    assert.ok(html.includes('id="hubResultCount"'), 'filtered result count')
    assert.ok(!html.includes('class="hub-intro"'), 'duplicate type intro removed')
    assert.ok(!html.includes('id="hubPageTitle"'), 'duplicate type title removed')
    assert.ok(html.includes('class="hub-nav"'), 'workbench-style top navigation')
    assert.ok(html.includes('class="hub-nav-title"'), 'capability hub navigation title')
    assert.ok(html.includes('data-icon="capabilityStack"'), 'capability navigation icon')
    assert.ok(html.includes('data-tab="experts"'), 'experts tab')
    assert.ok(html.includes('data-tab="skills"'), 'skills tab')
    assert.ok(html.includes('data-tab="connectors"'), 'connectors tab')
    assert.ok(html.includes('MCP 连接器'), 'MCP connector label')
    assert.ok(html.includes('data-tab="experts" aria-selected="true"'), 'experts default tab')
    assert.ok(html.includes('id="hubGrid"'), 'card grid')
    assert.ok(html.includes('id="hubFeatured"'), 'featured section')
    assert.ok(html.includes('id="hubChips"'), 'category chips')
    assert.ok(html.includes('id="hubInstalledOnly"'), 'installed filter')
    assert.ok(html.includes('id="hubDrawer"'), 'detail drawer')
    assert.ok(html.includes('id="hubAddDialog"'), 'add dialog')
    assert.ok(html.includes('data-add-panel="local"'), 'local import')
    assert.ok(html.includes('data-add-panel="cursor-repo"'), 'Cursor repository import')
    assert.ok(html.includes('id="hubRepoPreview"'), 'Cursor repository preview')
    assert.ok(html.includes('data-add-panel="zip"'), 'zip import')
    assert.ok(html.includes('data-add-panel="https"'), 'https import')
    assert.ok(html.includes('data-add-panel="custom"'), 'custom wizard')
    assert.ok(html.includes('capability-hub.css'), 'stylesheet link')
    assert.ok(html.includes('capability-hub.js'), 'script link')
  })

  it('css defines the KnowMe responsive catalog system', () => {
    assert.ok(css.includes('grid-template-columns: repeat(2'), '2-col catalog')
    assert.ok(css.includes('@media (max-width: 860px)'), 'desktop collapse breakpoint')
    assert.ok(css.includes('@media (max-width: 620px)'), 'single-column breakpoint')
    assert.ok(css.includes('--hub-bg: #f3f1ed'), 'warm restrained palette')
    assert.ok(css.includes('prefers-reduced-motion'), 'reduced motion support')
    assert.ok(css.includes('background: #2f7461'), 'workbench green active tab')
    assert.ok(css.includes('border-radius: 8px'), 'workbench tab group radius')
    assert.ok(css.includes('.hub-tab .ico { display: none; }'), 'workbench text-only tabs')
    assert.ok(css.includes('.hub-nav {'), 'workbench-style navigation bar')
    assert.ok(css.includes('height: 44px'), 'workbench navigation height')
    assert.ok(css.includes('background: #fbfaf7'), 'workbench navigation surface')
    assert.ok(css.includes('body.hub-embedded .hub-nav { display: none; }'), 'embedded page hides duplicate navigation')
  })

  it('js resolves knowme/api bridge with mock fallback', () => {
    assert.ok(js.includes('window.knowme'), 'knowme bridge')
    assert.ok(js.includes('cap.list'), 'capability.list')
    assert.ok(js.includes('cap?.install') || js.includes('cap.install'), 'capability.install')
    assert.ok(js.includes('cap?.uninstall') || js.includes('cap.uninstall'), 'capability.uninstall')
    assert.ok(js.includes('cap?.enable') || js.includes('cap.enable'), 'capability.enable')
    assert.ok(js.includes('cap?.disable') || js.includes('cap.disable'), 'capability.disable')
    assert.ok(js.includes('cap?.update') || js.includes('cap.update'), 'capability.update')
    assert.ok(js.includes('cap?.import') || js.includes('cap.import'), 'capability.import')
    assert.ok(js.includes('scanCursorRepository'), 'Cursor repository scan')
    assert.ok(js.includes('importCursorRepository'), 'Cursor repository import')
    assert.ok(js.includes('trustConfirmed'), 'explicit local trust retry')
    assert.ok(js.includes('expert?.tryChat') || js.includes('expert.tryChat'), 'expert.tryChat')
    assert.ok(js.includes('connector?.health') || js.includes('connector.health'), 'connector.health')
    assert.ok(js.includes('toolsPreview'), 'connector.toolsPreview')
    assert.ok(js.includes('migrateLegacy'), 'skill.migrateLegacy wizard')
    assert.ok(js.includes('hubConnectorExtras'), 'connector drawer extras')
    assert.ok(js.includes('MOCK_CATALOG'), 'offline mock catalog')
    assert.ok(js.includes('capability-hub-close'), 'parent close message')
    assert.ok(js.includes('capability-hub-tab'), 'parent tab sync')
    assert.ok(js.includes("document.body.classList.toggle('hub-embedded'"), 'embedded mode class')
    assert.ok(js.includes("tab: 'experts'"), 'experts default state')
    assert.ok(js.includes("return 'experts'"), 'experts direct-page default')
  })

  it('js handles empty, error and offline states', () => {
    assert.ok(js.includes('hub-state error'), 'error state markup')
    assert.ok(css.includes('.hub-state.offline') || js.includes("' offline'"), 'offline state markup')
    assert.ok(js.includes('没有找到匹配能力'), 'empty search state')
    assert.ok(js.includes('hub-skeleton'), 'layout-matched loading skeleton')
    assert.ok(js.includes('data-clear-filters'), 'clear filter recovery action')
    assert.ok(js.includes('loadError'), 'error tracking')
    assert.ok(js.includes('state.offline'), 'offline flag')
  })
})
