/**
 * capability-hub — 静态 DOM 契约与 bridge fallback
 */
const { describe, it } = require('node:test')
const assert = require('node:assert')
const fs = require('fs')
const path = require('path')

const root = path.join(__dirname, '..', 'src')
const html = fs.readFileSync(path.join(root, 'capability-hub.html'), 'utf8')
const js = fs.readFileSync(path.join(root, 'capability-hub.js'), 'utf8')
const css = fs.readFileSync(path.join(root, 'capability-hub.css'), 'utf8')
const pickerJs = fs.readFileSync(path.join(root, 'lib', 'catalog-picker.js'), 'utf8')

describe('capability hub static contract', () => {
  it('html shell includes tabs, search, grid, drawer, add dialog', () => {
    assert.ok(html.includes('id="hubSearch"'), 'search input')
    assert.ok(html.includes('id="hubResultCount"'), 'filtered result count')
    assert.ok(!html.includes('class="hub-intro"'), 'duplicate type intro removed')
    assert.ok(!html.includes('id="hubPageTitle"'), 'duplicate type title removed')
    assert.ok(html.includes('class="hub-nav"'), 'workbench-style top navigation')
    assert.ok(html.includes('class="hub-nav-title"'), 'capability hub navigation title')
    assert.ok(html.includes('data-icon="capabilityStack"'), 'capability navigation icon')
    assert.ok(html.includes('data-tab="experts"'), 'experts tab')
    assert.ok(html.includes('data-tab="skills"'), 'skills tab')
    assert.ok(html.includes('data-tab="connectors"'), 'connectors tab')
    assert.ok(html.includes('MCP 连接器'), 'MCP connector label')
    assert.ok(html.includes('data-tab="experts" aria-selected="true"'), 'experts default tab')
    assert.ok(html.includes('id="hubGrid"'), 'card grid')
    assert.ok(html.includes('id="hubFeatured"'), 'featured section')
    assert.ok(html.includes('id="hubChips"'), 'category chips')
    assert.ok(!html.includes('按场景浏览'), 'compact toolbar drops scene label')
    assert.ok(html.includes('class="hub-commandbar"'), 'command bar hosts search + chips')
    assert.ok(!html.includes('class="hub-toolbar"'), 'legacy toolbar row removed')
    assert.ok(html.includes('id="hubInstalledOnly"'), 'installed filter')
    assert.ok(html.includes('id="hubDrawer"'), 'detail drawer')
    assert.ok(html.includes('id="hubAddDialog"'), 'add dialog')
    assert.ok(html.includes('id="hubExpertDialog"'), 'expert editor dialog')
    assert.ok(html.includes('id="hubPickerDialog"'), 'catalog picker dialog')
    assert.ok(html.includes('lib/catalog-picker.js'), 'loads reusable catalog picker')
    assert.ok(html.includes('data-add-panel="local"'), 'local import')
    assert.ok(html.includes('data-add-panel="cursor-repo"'), 'Cursor repository import')
    assert.ok(html.includes('id="hubRepoPreview"'), 'Cursor repository preview')
    assert.ok(html.includes('data-add-panel="zip"'), 'zip import')
    assert.ok(html.includes('data-add-panel="https"'), 'https import')
    assert.ok(html.includes('data-add-panel="custom"'), 'custom wizard')
    assert.ok(html.includes('lib/capability-hub-icons.js'), 'loads domain icon resolver')
    assert.ok(html.includes('capability-hub.css'), 'stylesheet link')
    assert.ok(html.includes('capability-hub.js'), 'script link')
    assert.ok(html.includes('lib/agent-identity.js'), 'loads shared agent identity / preset avatars')
  })

  it('css defines the KnowMe responsive catalog system', () => {
    assert.match(css, /\.hub-featured-row\s*\{[^}]*grid-template-columns: repeat\(3, minmax\(0, 1fr\)\)/s, '3-col featured catalog')
    assert.match(css, /\.hub-grid\s*\{[^}]*grid-template-columns: repeat\(3, minmax\(0, 1fr\)\)/s, '3-col capability catalog')
    assert.match(css, /@media \(max-width: 860px\)[\s\S]*?\.hub-featured-row,\s*\.hub-grid\s*\{\s*grid-template-columns: repeat\(2, minmax\(0, 1fr\)\)/, 'medium-width 2-col grids')
    assert.ok(css.includes('@media (max-width: 620px)'), 'single-column breakpoint')
    assert.match(css, /@media \(max-width: 620px\)[\s\S]*?\.hub-featured-row,\s*\.hub-grid\s*\{\s*grid-template-columns: 1fr/, 'narrow-width single-column grids')
    assert.ok(css.includes('--hub-bg: #f3f1ed'), 'warm restrained palette')
    assert.ok(css.includes('prefers-reduced-motion'), 'reduced motion support')
    assert.ok(css.includes('background: #2f7461'), 'workbench green active tab')
    assert.ok(css.includes('border-radius: 8px'), 'workbench tab group radius')
    assert.ok(css.includes('.hub-tab .ico { display: none; }'), 'workbench text-only tabs')
    assert.ok(css.includes('.hub-nav {'), 'workbench-style navigation bar')
    assert.match(css, /\.hub-nav\s*\{\s*height:\s*52px;\s*min-height:\s*52px/, 'workbench navigation height')
    assert.ok(css.includes('background: #fbfaf7'), 'workbench navigation surface')
    assert.ok(css.includes('body.hub-embedded .hub-nav { display: none; }'), 'embedded page hides duplicate navigation')
    assert.ok(css.includes('.hub-avatar-picker'), 'expert avatar picker styles')
    assert.ok(css.includes('overflow-x: auto'), 'avatar picker scrolls horizontally')
    assert.ok(css.includes('.hub-select-sep'), 'AgenticType option dividers')
    assert.ok(css.includes('.hub-flag-row'), 'agentic checkbox row')
    assert.ok(css.includes('width: min(920px, calc(100vw - 32px))'), 'expert editor is enlarged')
    assert.ok(css.includes('.hub-avatar-photo'), 'expert card photo styles')
    assert.match(css, /\.hub-commandbar\s*\{\s*display:\s*flex/, 'search and scene chips share one row')
  })

  it('js resolves knowme/api bridge with mock fallback', () => {
    assert.ok(js.includes("skills: ['全部', '收藏', '写作', '游戏', '研发', '办公']"), 'skill chips use work domains + favorites')
    assert.ok(!js.includes("skills: ['全部', '写作', '飞书', '研发', '效率']"), 'skill chips drop Feishu/efficiency')
    assert.ok(js.includes("connectors: ['全部', '收藏', '飞书', 'MCP', '知识库', '自定义']"), 'connector chips keep Feishu + favorites')
    assert.ok(js.includes('function toggleFavoriteFromButton'), 'favorite toggle handler')
    assert.ok(js.includes('hub-card-fav'), 'favorite star on cards')
    assert.ok(js.includes('FAVORITE_CATEGORY'), 'favorites category filter')
    assert.ok(js.includes('cats.some((cat) => String(cat) === state.category)'), 'category filter matches categories array')
    assert.ok(js.includes('window.knowme'), 'knowme bridge')
    assert.ok(js.includes('cap.list'), 'capability.list')
    assert.ok(js.includes('cap?.install') || js.includes('cap.install'), 'capability.install')
    assert.ok(js.includes('cap?.uninstall') || js.includes('cap.uninstall'), 'capability.uninstall')
    assert.ok(js.includes('cap?.enable') || js.includes('cap.enable'), 'capability.enable')
    assert.ok(js.includes('cap?.disable') || js.includes('cap.disable'), 'capability.disable')
    assert.ok(js.includes('cap?.update') || js.includes('cap.update'), 'capability.update')
    assert.ok(js.includes('cap?.import') || js.includes('cap.import'), 'capability.import')
    assert.ok(js.includes('scanCursorRepository'), 'Cursor repository scan')
    assert.ok(js.includes('importCursorRepository'), 'Cursor repository import')
    assert.ok(js.includes('trustConfirmed'), 'explicit local trust retry')
    assert.ok(js.includes('riskConfirmed'), 'explicit high-risk confirmation')
    const governedRiskChecks = js.match(/\['high', 'critical'\]\.includes\(it\.risk\?\.level\)/g) || []
    assert.ok(governedRiskChecks.length >= 3, 'install, enable and install-and-start confirm high/critical risk')
    assert.ok(js.includes('function originLabel'), 'original identifier helper')
    assert.ok(js.includes('<dt>原始标识</dt>'), 'original identifier in drawer metadata')
    assert.ok(js.includes('[it.name, it.originName, it.id'), 'search matches display name and original identifier')
    assert.ok(js.includes('<h3>权限</h3>'), 'permission governance section')
    assert.ok(js.includes('<h3>输入 / 输出</h3>'), 'input and output governance section')
    assert.ok(js.includes('<h3>风险与来源</h3>'), 'risk and provenance governance section')
    assert.ok(js.includes('安装并开始'), 'available expert CTA')
    assert.ok(js.includes('启用并开始'), 'disabled expert CTA')
    assert.ok(js.includes('开始对话'), 'enabled expert CTA')
    assert.ok(js.includes('capability-hub-start-expert'), 'expert start intent')
    assert.ok(js.includes('capability-hub-start-expert-result'), 'expert start result')
    assert.ok(js.includes('添加到工作台'), 'expert workbench action')
    assert.ok(js.includes('capability-hub-add-expert-to-workbench'), 'expert workbench intent')
    assert.ok(js.includes('capability-hub-add-expert-to-workbench-result'), 'expert workbench result')
    assert.ok(js.includes("surface: 'capability'"), 'default detail surface is capability')
    assert.ok(js.includes("state.surface === 'workbench'"), 'workbench surface branches expert actions')
    assert.ok(js.includes('function applyExpertSelection'), 'deep-link expert selection helper')
    assert.ok(js.includes('capability-hub-select-expert'), 'parent can select expert without reload')
    assert.ok(js.includes('parseInitialDeepLink'), 'reads expertId and surface from query')
    assert.ok(js.includes('flushPendingExpertSelection'), 'opens pending expert after catalog load')
    assert.ok(js.includes('pendingParentRequests'), 'parent request lifecycle')
    assert.ok(js.includes('workbenchExpertIds'), 'already-bound state')
    assert.ok(js.includes('api?.workbenchModeList'), 'active workbench bindings are synchronized')
    assert.ok(js.includes('activeMode?.bindings'), 'active mode drives already-bound state')
    assert.ok(js.indexOf('await requestWorkbenchAdd(it.id)') < js.indexOf('state.workbenchExpertIds.add(it.id)'), 'binding is confirmed before local already-bound state changes')
    assert.match(js, /if \(capabilityPrepared\) \{\s*await loadCatalog\(\)\s*openDrawer\(it\.id\)/, 'installed capability state survives a later binding or trial failure')
    assert.ok(js.includes("toast(e?.message || '操作失败', 'error')"), 'binding failure remains retryable')
    assert.ok(!js.includes('api?.expertTryChat') && !js.includes('expert?.tryChat'), 'renderer no longer creates orphan try-chat')
    assert.ok(js.includes('connector?.health') || js.includes('connector.health'), 'connector.health')
    assert.ok(js.includes('toolsPreview'), 'connector.toolsPreview')
    assert.ok(js.includes('migrateLegacy'), 'skill.migrateLegacy wizard')
    assert.ok(js.includes('hubConnectorExtras'), 'connector drawer extras')
    assert.ok(js.includes('hubExpertDialog'), 'expert editor dialog')
    assert.ok(js.includes('openExpertEditor'), 'expert create/tune/copy editor')
    assert.ok(js.includes('saveExpertEditor'), 'expert save handler')
    assert.ok(js.includes('deleteExpertEditor'), 'expert delete handler')
    assert.ok(js.includes('canDeleteEditedExpert'), 'only self-built experts may delete from editor')
    assert.ok(js.includes('function isUserCreatedExpert'), 'user-created expert predicate')
    assert.ok(html.includes('id="hubExpertDelete"'), 'expert delete button in editor footer')
    assert.ok(html.includes('删除专家'), 'delete expert label')
    assert.ok(css.includes('.hub-btn.danger'), 'danger button style for delete')
    assert.ok(js.includes('function expertAvatarMark'), 'expert cards render preset photos')
    assert.ok(js.includes('data-avatar-id'), 'expert editor exposes avatar picker')
    assert.ok(js.includes('autoMatchExpertAvatar'), 'avatar auto-match from expert attributes')
    assert.ok(!js.includes('data-avatar-auto'), 'create form does not show match-by-name button')
    assert.ok(js.includes('suggestExpertAvatarKey'), 'suggests avatar key from name/description/skills')
    assert.ok(!js.includes("avatar: editor.detail?.avatar || '🧩'"), 'no emoji avatar default on save')
    assert.ok(js.includes('renderAddButton'), 'add button label is tab-aware')
    assert.ok(js.includes('btn.hidden = isExpert'), 'experts tab hides search-bar create button')
    assert.ok(js.includes('function createExpertCardHtml'), 'mine filter has create-expert card helper')
    assert.ok(js.includes('data-create-expert'), 'create expert card marker')
    assert.ok(js.includes('创建专家'), 'create expert card label')
    assert.ok(js.includes('hub-card-create'), 'create expert card class')
    assert.ok(css.includes('.hub-card.hub-card-create'), 'create expert dashed card styles')
    assert.ok(html.includes('id="hubBtnAdd" hidden') || html.includes('id="hubBtnAdd" hidden>'), 'add button hidden by default on experts')
    assert.ok(js.includes('agentProfileSave'), 'agent profile persistence')
    assert.ok(!/\bMOCK_CATALOG\b/.test(js), 'mock catalog constant fully removed')
    assert.ok(js.includes('capability-hub-close'), 'parent close message')
    assert.ok(js.includes('capability-hub-tab'), 'parent tab sync')
    assert.ok(js.includes("document.body.classList.toggle('hub-embedded'"), 'embedded mode class')
    assert.ok(js.includes("tab: 'experts'"), 'experts default state')
    assert.ok(js.includes("return 'experts'"), 'experts direct-page default')
    assert.ok(js.includes("experts: ['全部', '收藏', '办公', '写作', '研发', '知识', '我的']"), 'mine chip in expert scenario filters')
    assert.ok(js.includes('MINE_EXPERT_CATEGORY'), 'mine category constant')
    assert.ok(js.includes('function isMineFilterActive'), 'mine filter helper')
    assert.ok(js.includes('function isUserCreatedExpert'), 'user-created expert predicate')
    assert.ok(js.includes('function canDeleteEditedExpert'), 'delete gated for self-built tune editor')
    assert.ok(js.includes('function matchesCategoryFilter'), 'category/mine match helper')
    assert.ok(js.includes("state.category = MINE_EXPERT_CATEGORY"), 'save switches to mine filter')
    assert.ok(js.includes('我创建的专家'), 'mine catalog title')
    assert.ok(js.includes("if (!['local', 'custom'].includes(String(it.source || ''))) return false"), 'mine excludes local-repo/zip imports')
    assert.ok(js.includes('repositoryId'), 'mine excludes linked repository experts')
  })

  it('expert detail actions are surface-aware', () => {
    const start = js.indexOf('const isCurated = isCuratedExpert(it)')
    const end = js.indexOf('if (window.StickyIcons)', start)
    const actions = js.slice(start, end)
    assert.ok(actions.includes("state.surface === 'workbench'"), 'workbench branch in drawer actions')
    assert.ok(actions.includes("data-act=\"startExpert\""), 'workbench keeps start CTA')
    assert.ok(actions.includes('工作台撤回'), 'bound state withdraw label')
    assert.ok(actions.includes("data-act=\"removeExpert\""), 'capability surface withdraw CTA')
    assert.ok(actions.includes("data-act=\"addExpert\""), 'capability surface bind CTA')
    assert.ok(actions.includes("data-act=\"copyExpert\""), 'curated copy action')
    assert.ok(actions.includes("data-act=\"editExpert\""), 'editable edit action')
    assert.ok(actions.includes('>编辑<'), 'edit label uses 编辑 not 调优')
    assert.ok(!actions.includes('>调优<'), 'does not use 调优 label on expert actions')
    assert.ok(!actions.includes('已在工作台'), 'no disabled already-bound label')
    const workbenchBranch = actions.slice(actions.indexOf("state.surface === 'workbench'"), actions.indexOf('expertInWorkbench'))
    assert.ok(workbenchBranch.includes('startExpert'), 'workbench primary is start')
    assert.ok(!workbenchBranch.includes('editExpert'), 'workbench surface omits edit')
    assert.ok(!workbenchBranch.includes('工作台撤回'), 'workbench surface omits withdraw')
    assert.ok(!workbenchBranch.includes('copyExpert'), 'workbench surface omits copy')
    const capabilityBranch = actions.slice(actions.indexOf('expertInWorkbench'), actions.indexOf('expertActions ||'))
    assert.ok(capabilityBranch.includes('addExpert'), 'capability can add to workbench')
    assert.ok(capabilityBranch.includes('removeExpert'), 'capability can withdraw from workbench')
    assert.ok(!capabilityBranch.includes('startExpert'), 'capability surface omits start conversation')
    assert.ok(!capabilityBranch.includes('data-act="update"'), 'experts omit update')
    assert.ok(!capabilityBranch.includes('data-act="uninstall"'), 'experts omit uninstall')
  })

  it('supports detail-only presentation for workbench overlay', () => {
    assert.ok(js.includes("presentation: 'hub'"), 'presentation state defaults to hub')
    assert.ok(js.includes('function parsePresentation'), 'parses presentation query')
    assert.ok(js.includes('function applyPresentation'), 'applies presentation class')
    assert.ok(js.includes('hub-detail-only'), 'detail-only body class')
    assert.ok(js.includes("state.presentation === 'detail'"), 'detail presentation closes hub with drawer')
    assert.ok(js.includes("reason: 'detail-dismiss'"), 'detail close uses detail-dismiss reason')
    assert.ok(js.includes('function dismissDetailOverlay'), 'detail overlay dismiss helper')
    assert.ok(js.includes("closeHub({ reason: 'detail-dismiss' })"), 'dismiss posts close before flipping presentation')
    assert.ok(js.includes('function clearBrowseSelection'), 'browse mode clears residual workbench detail')
    assert.ok(css.includes('body.hub-detail-only'), 'detail-only shell styles exist')
  })

  it('expert editor dialog is grouped, scannable and validated', () => {
    assert.ok(html.includes('id="hubExpertSummary"'), 'footer selection summary node')
    assert.ok(html.includes('class="hub-dialog-foot-actions"'), 'footer actions are grouped beside the summary')
    assert.ok(js.includes('renderCatalogSummaries'), 'catalog summaries on the editor form')
    assert.ok(js.includes('openCatalogPicker'), 'catalog selection opens a dialog')
    assert.ok(js.includes('data-open-picker'), 'summary exposes picker trigger')
    assert.ok(js.includes('请先安装技能，再选择要装配的能力。'), 'empty skills guides install-then-select')
    assert.ok(js.includes('hub-select-sep'), 'AgenticType options are divided')
    assert.ok(js.includes('class="hub-flag"'), 'agentic checkboxes use aligned flag rows')
    assert.ok(pickerJs.includes('data-count-for='), 'per-group selected/total badge')
    assert.ok(pickerJs.includes('data-pick-all='), 'group select-all action')
    assert.ok(pickerJs.includes('data-pick-none='), 'group clear action')
    assert.ok(js.includes('updateExpertEditorSelection'), 'selection summary stays in sync')
    assert.ok(js.includes('markExpertFieldInvalid'), 'required field highlight')
    assert.match(js, /markExpertFieldInvalid\(id \? 'name' : 'id'\)/, 'save focuses the missing required field')
    assert.ok(js.includes('class="hub-req"'), 'required marker')
    assert.ok(pickerJs.includes('hub-picker-empty'), 'empty capability placeholder')
    assert.ok(pickerJs.includes('const BROWSE_THRESHOLD = 9'), 'large catalogs switch to browse mode')
    assert.ok(pickerJs.includes('data-picker-search='), 'per-group search input')
    assert.ok(pickerJs.includes('data-picker-selected='), 'only-selected review toggle')
    assert.ok(pickerJs.includes('function filter'), 'group filtering')
    assert.ok(pickerJs.includes('hub-check-subgroup'), 'category subgroups for large catalogs')
    assert.ok(pickerJs.includes('.hub-check:not([hidden]) input'), 'bulk actions apply to visible options only')
    assert.match(css, /\.hub-check-scroll\s*\{[^}]*max-height: 244px/s, 'large selection lists are height-bounded')
    assert.ok(css.includes('.hub-check-subgroup h4'), 'subgroup heading style')
    assert.ok(css.includes(".hub-toggle-mini[aria-pressed='true']"), 'only-selected toggle pressed state')
    assert.ok(js.includes('<h3>基础信息</h3>'), 'basics group')
    assert.ok(js.includes("title: 'Tool 与连接器'"), 'tool group title')
    assert.match(css, /\.hub-check-grid\s*\{[^}]*grid-template-columns: repeat\(auto-fill, minmax\(188px, 1fr\)\)/s, 'multi-column selection grid')
    assert.match(css, /\.hub-expert-dialog \.hub-dialog-body\s*\{[^}]*padding: 22px 24px 24px/s, 'dialog body aligns with head and foot')
    assert.ok(css.includes('.hub-check:has(input:checked)'), 'selected card state')
    assert.ok(css.includes('.hub-check input:focus-visible + .hub-check-box'), 'keyboard focus state')
    assert.ok(css.includes('.hub-field.invalid input'), 'invalid field style')
    assert.match(css, /@media \(max-width: 760px\)[\s\S]*?\.hub-check-grid \{ grid-template-columns: repeat\(auto-fill, minmax\(150px, 1fr\)\)/, 'narrow-width selection grid')
  })

  it('js handles empty, error and offline states', () => {
    assert.ok(js.includes('hub-state error'), 'error state markup')
    assert.ok(css.includes('.hub-state.offline') || js.includes("' offline'"), 'offline state markup')
    assert.ok(js.includes('没有找到匹配能力'), 'empty search state')
    assert.ok(js.includes('hub-skeleton'), 'layout-matched loading skeleton')
    assert.ok(js.includes('data-clear-filters'), 'clear filter recovery action')
    assert.ok(js.includes('loadError'), 'error tracking')
    assert.ok(js.includes('state.offline'), 'offline flag')
  })

  it('bounds search rerenders and card entrance delays', () => {
    assert.ok(js.includes('const SEARCH_DEBOUNCE_MS = 120'), 'search debounce constant')
    assert.ok(js.includes('clearTimeout(searchRenderTimer)'), 'search timer is coalesced')
    assert.match(js, /searchRenderTimer = setTimeout\([\s\S]*SEARCH_DEBOUNCE_MS/, 'search render is deferred')
    assert.ok(js.includes('function maybeArmExpertCardEnter'), 'first-enter arm helper')
    assert.ok(js.includes('expertCardEnterPlayed'), 'enter plays once per session')
    assert.ok(css.includes('.hub-featured-row.is-entering .hub-featured-card'), 'featured enter is gated')
    assert.ok(css.includes('.hub-grid.is-entering .hub-card'), 'catalog enter is gated')
    assert.equal(
      (css.match(/animation-delay: min\(calc\(var\(--index, 0\) \* \d+ms\), 120ms\);/g) || []).length,
      2,
      'featured and catalog animation delays are capped',
    )
  })

  it('paints primary catalog before auxiliary hub data', () => {
    assert.ok(js.includes('async function loadCatalogAuxiliaries'), 'auxiliary loader')
    assert.ok(js.includes('void loadCatalogAuxiliaries()'), 'auxiliaries are non-blocking')
    assert.ok(js.includes('async function loadCatalog(opts = {})'), 'loadCatalog accepts soft option')
    assert.ok(js.includes('const soft = !!opts.soft'), 'soft refresh skips skeleton')
    assert.ok(js.includes("data.type === 'capability-hub-resume'"), 'handles host resume')
    assert.ok(js.includes('function resumeFromHost'), 'resume syncs without cold reload')
    assert.ok(
      !/await loadExpertEditorCatalog\(\)\s*\n\s*await loadCompositionIndex\(\)/.test(js),
      'primary load no longer awaits auxiliaries serially',
    )
  })

  it('avoids double catalog paint after auxiliaries and same-tab resume', () => {
    const auxFn = js.match(/async function loadCatalogAuxiliaries\(\) \{[\s\S]*?\n  \}/)?.[0] || ''
    assert.ok(auxFn, 'auxiliary loader body')
    assert.ok(auxFn.includes('renderDrawer()'), 'auxiliaries update drawer')
    assert.ok(!auxFn.includes('renderGrid()'), 'auxiliaries must not repaint catalog grid')

    const resumeFn = js.match(/function resumeFromHost\([\s\S]*?\n  \}/)?.[0] || ''
    assert.ok(resumeFn, 'resumeFromHost body')
    assert.ok(resumeFn.includes('refreshWorkbenchExpertIds()'), 'resume refreshes workbench bindings')
    assert.ok(resumeFn.includes('renderDrawer()'), 'resume updates drawer')
    assert.ok(!resumeFn.includes('renderGrid()'), 'same-tab resume must not repaint grid')
    assert.ok(!resumeFn.includes('loadCatalog('), 'same-tab resume must not soft-reload catalog')
  })
})

describe('skill hub domain categories', () => {
  const {
    mapPackSkillToHub,
    mapCatalogItemToHub,
  } = require('../src/lib/capability-hub-service')
  const catalog = JSON.parse(fs.readFileSync(path.join(root, 'catalog', 'catalog.json'), 'utf8'))

  it('maps pack skills to work-domain primary categories', () => {
    const feishu = mapPackSkillToHub({ id: 'feishu-today-priority', name: '飞书今日优先级', ownerPackId: 'game-studio' })
    assert.equal(feishu.category, '办公')
    assert.ok(feishu.categories.includes('办公'))
    assert.ok(feishu.categories.includes('能力包'))

    const office = mapPackSkillToHub({ id: 'office-document', name: '办公文档', ownerPackId: 'game-studio' })
    assert.equal(office.category, '写作')

    const game = mapPackSkillToHub({ id: 'game-qa-acceptance', name: '游戏测试验收', ownerPackId: 'game-studio' })
    assert.equal(game.category, '游戏')
  })

  it('normalizes curated 开发 to 研发 and keeps code-review under 研发', () => {
    const review = catalog.entries.find((e) => e.id === 'code-review')
    assert.ok(review)
    assert.deepEqual(review.categories, ['研发'])

    const hub = mapCatalogItemToHub({ ...review, categories: ['开发'] })
    assert.equal(hub.category, '研发')
    assert.deepEqual(hub.categories, ['研发'])
  })
})

describe('capability hub icons and favorites store', () => {
  const { resolveCapabilityIcon } = require('../src/lib/capability-hub-icons')
  const {
    toggleFavorite,
    listFavoriteKeys,
    favoriteKey,
  } = require('../src/lib/capability-store')
  const os = require('os')
  const path = require('path')

  it('maps skill domains to representative icons', () => {
    assert.equal(resolveCapabilityIcon({ kind: 'skill', category: '写作' }).icon, 'pencilLine')
    assert.equal(resolveCapabilityIcon({ kind: 'skill', category: '游戏' }).icon, 'gamepad')
    assert.equal(resolveCapabilityIcon({ kind: 'skill', category: '研发' }).icon, 'code')
    assert.equal(resolveCapabilityIcon({ kind: 'skill', category: '办公' }).icon, 'clipboardCheck')
  })

  it('persists favorite toggles under capabilities/favorites.json', () => {
    const userData = fs.mkdtempSync(path.join(os.tmpdir(), 'km-fav-'))
    const first = toggleFavorite(userData, 'skill', 'writing-polish')
    assert.equal(first.ok, true)
    assert.equal(first.favorite, true)
    assert.ok(listFavoriteKeys(userData).includes(favoriteKey('skill', 'writing-polish')))
    const second = toggleFavorite(userData, 'skill', 'writing-polish')
    assert.equal(second.favorite, false)
    assert.ok(!listFavoriteKeys(userData).includes(favoriteKey('skill', 'writing-polish')))
  })
})
