const { describe, it } = require('node:test')
const assert = require('node:assert')
const fs = require('node:fs')
const path = require('node:path')

const read = file => fs.readFileSync(path.join(__dirname, '..', 'src', file), 'utf8')

describe('expert task chat workbench handoff', () => {
  const workbench = read('workbench.js')
  const workspace = read('workspace.js')
  const agent = read('workspace-agent.js')
  const hub = read('capability-hub.js')
  const html = read('workspace.html')
  const layout = read('workbench-layout.css')

  it('creates one expert Session and opens task-room without Agent Graph confirmation', () => {
    const start = workbench.indexOf('async function submitTaskComposer()')
    const end = workbench.indexOf('async function openTaskFromRecent', start)
    const submit = workbench.slice(start, end)
    assert.ok(workbench.includes('async function beginExpertTask('), 'shared expert-task starter')
    assert.ok(submit.includes('await beginExpertTask({'), 'task composer uses shared starter')
    assert.ok(workbench.includes("execRef: { kind: 'session', id: result.session.id }"), 'task links to the Session')
    assert.ok(workbench.includes('openExpertTaskRoom(updatedTask, result.session, resolvedExpert, resolvedWorkflow)'), 'successful handoff opens embedded chat room')
    assert.ok(!submit.includes('launchAgentRun('), 'single-expert task skips Agent Graph flow')
    assert.ok(workspace.includes('startExpertTaskChat'), 'workspace owns workbench-to-agent handoff')
    assert.ok(workspace.includes('WorkspaceAgent?.startExpertChat?.({'), 'host starts a persistent expert Session')
  })

  it('prefills the task goal and restores the same Session from recent tasks', () => {
    assert.ok(agent.includes('draftsBySession.set(created.id, draft)'), 'task goal is stored as a Session draft')
    assert.ok(agent.includes('aiInput.value = draft'), 'task goal appears in the real Composer')
    assert.ok(workbench.includes("task.execRef?.kind === 'session'"), 'recent task recognizes Session execution refs')
    assert.ok(workbench.includes('await onExpertTaskResume({ task, sessionId: task.execRef.id, expert })'), 'recent task resumes instead of duplicating')
    assert.ok(workspace.includes('WorkspaceAgent?.resumeSession?.(sessionId)'), 'workspace resumes the authoritative Session')
  })

  it('shows expert context and supports Session-scoped knowledge selection', () => {
    for (const label of ['专家属性', '专业能力', '技能与连接器', '知识库']) {
      assert.ok(agent.includes(label), `expert context panel includes ${label}`)
    }
    assert.ok(agent.includes('function renderExpertContextPanelHtml'), 'properties live in a dedicated side panel helper')
    assert.ok(agent.includes('agent-empty-expert-split'), 'assistant chat shows properties to the right of the dialog')
    assert.ok(agent.includes('isWorkbenchExpertTaskRoomActive'), 'workbench task room leaves properties to the right panel')
    assert.ok(workbench.includes('id="wbTaskComposerKnowledge"'), 'task composer exposes knowledge choices')
    assert.ok(workbench.includes('wb-task-expert-picker'), 'expert picker uses brief card control')
    assert.ok(workbench.includes('data-task-composer="close"'), 'composer has header close')
    assert.ok(!workbench.includes('data-task-composer="cancel"'), 'composer no longer shows cancel')
    assert.ok(workbench.includes('wb-task-composer-actions'), 'primary action is in dedicated footer')
    assert.ok(workbench.includes('id="wbTaskComposerScheduleEnabled"'), 'composer exposes optional schedule toggle')
    assert.ok(workbench.includes('function readTaskComposerSchedule'), 'composer reads schedule payload')
    {
      const openStart = workbench.indexOf('function openTaskComposer(')
      const openEnd = workbench.indexOf('function closeTaskComposer(', openStart)
      const openBody = workbench.slice(openStart, openEnd)
      assert.ok(openBody.includes("goalInput.value = String(goal || '')"), 'new composer does not backfill pendingGoal')
      assert.ok(!openBody.includes('pendingGoal'), 'stale pendingGoal no longer prefills composer goal')
    }
    assert.ok(layout.includes('.wb-task-knowledge-option input[type="checkbox"]'), 'knowledge checkboxes escape studio field stretch')
    assert.ok(layout.includes('.wb-task-composer-schedule'), 'composer schedule block is styled')
    assert.ok(layout.includes('.wb-task-composer-modal .wb-modal-body'), 'composer body does not stretch empty space')
    assert.ok(agent.includes('data-knowledge-provider='), 'expert conversation exposes provider toggles')
    assert.ok(html.includes('id="agentSessionKnowledgeBtn"'), 'knowledge scope remains editable after conversation starts')
    assert.ok(agent.includes('function syncKnowledgeToolbar()'), 'persistent knowledge control follows the active expert Session')
    assert.ok(agent.includes('agentSessionContextUpdate'), 'provider changes use the restricted Session IPC')
    assert.ok(agent.includes('window.Workbench?.updateExpertTaskRoom?.(activeSession)'), 'right-side task projection follows Session scope')
  })

  it('keeps a distinct non-Run detail projection in the workbench split layout', () => {
    assert.ok(html.includes('id="wbExpertTaskRoom"'), 'dedicated expert task detail surface exists')
    assert.ok(html.includes('id="wbExpertTaskBody"'), 'task detail projection has a render host')
    assert.ok(html.includes('id="wbExpertTaskTitle"'), 'expert room head has a title')
    assert.ok(html.includes('id="agentDialogueStatusBar"'), 'task-room dialogue status bar exists')
    assert.ok(html.includes('id="agentDialogueStatusBack"'), 'dialogue status bar has back control')
    assert.ok(html.includes('id="agentDialogueStatusState"'), 'unified chrome carries status state')
    assert.ok(layout.includes('.wb-expert-task-room'), 'task detail surface is styled')
    assert.ok(layout.includes('.agent-dialogue-status-bar'), 'dialogue status bar is styled')
    assert.ok(layout.includes('grid-column: 1 / -1'), 'dialogue status bar spans both columns')
    assert.ok(layout.includes('height: 52px'), 'dialogue status bar matches wb-head height')
    assert.ok(layout.includes('.wb-run-topbar'), 'run topbar rules remain for non-task-room')
    assert.ok(
      /\[data-workbench-layout="task-room"\][\s\S]{0,200}\.wb-run-topbar[\s\S]{0,80}display:\s*none !important/.test(layout),
      'task-room hides duplicate right topbars'
    )
    assert.ok(workbench.includes('wb-side-stack'), 'right panel uses visual side stack')
    assert.ok(workbench.includes('技能'), 'right panel shows skill snapshot')
    assert.ok(workbench.includes('连接器'), 'right panel shows connector snapshot')
    assert.ok(!workbench.includes('wb-expert-task-attr-grid'), 'legacy text-heavy attr grid removed')
    assert.ok(!html.includes('id="wbExpertTaskBack"'), 'duplicate back button removed from expert room')
    assert.ok(workbench.includes('function syncDialogueStatusBar('), 'dialogue status bar sync exists')
    assert.ok(workbench.includes('leaveDialogueTaskRoom'), 'dialogue status back uses shared leave path')
    assert.ok(workbench.includes("resolvedWorkflow ? 'workflow-chat' : 'expert-chat'"), 'task room distinguishes workflow vs expert chat modes')
    assert.ok(workspace.includes("setSurfaceMode(workbenchOn ? 'workbench' : 'agent')"), 'workbench stays on workbench session surface')
    assert.ok(workspace.includes("surface: 'workbench'"), 'expert task chat creates sessions on workbench surface')
    assert.ok(workspace.includes('勿再套一层'), 'expert/workflow rooms skip legacy workbench commander session')
    assert.ok(workbench.includes('data-side-manage="connectors"'), 'side rail can manage connectors')
    assert.ok(workbench.includes('data-side-manage="skills"'), 'side rail can manage skills')
    assert.ok(workbench.includes('data-side-manage="knowledge"'), 'side rail can manage knowledge')
    assert.ok(agent.includes("kind === 'expert-chat'"), 'expert-chat empty state branches before workflow guide')
    assert.ok(agent.includes('renderExpertCollabEmptyState'), 'workbench expert room uses collab empty state')
    assert.ok(agent.includes('agent-empty-expert-collab'), 'collab empty state is stylable without assistant launch classes')
    assert.ok(agent.includes('协作引导'), 'workflow empty-state kicker still exists for non-expert rooms')
    assert.ok(hub.includes('hubExpertSoul'), 'hub editor captures Soul')
    assert.ok(hub.includes('hubExpertSop'), 'hub editor captures SOP')
    assert.ok(hub.includes('hubExpertAgenticType'), 'hub editor captures AgenticType')
    assert.ok(hub.includes('AGENTIC_TYPE_OPTIONS'), 'hub exposes five agentic type options')
    assert.ok(layout.includes('.wb-side-manage-panel'), 'side manage panel is styled')
    assert.ok(layout.includes('.agent-empty-expert-collab'), 'collab empty state has dedicated styles')
    // 首屏挂载真实 Composer：外层 foot 透明，边框只在 .agent-composer，避免叠影双边框
    assert.ok(
      layout.includes('.agent-empty-expert-collab .agent-home-composer-mount .agent-col-foot'),
      'collab launch foot is scoped under the composer mount'
    )
    assert.ok(
      layout.includes('.agent-empty-expert-collab .agent-home-composer-mount .agent-composer'),
      'collab launch chrome lives on the composer shell only'
    )
    assert.ok(workbench.includes('btnDialogueStatusBack'), 'dialogue status back is wired')
    assert.ok(workbench.includes('if (expertTaskRoom)'), 'leave path still closes expert task room')
  })

  it('workbench expert start creates a task room instead of assistant chat', () => {
    assert.ok(workbench.includes('async function startExpertTaskDirect('), 'workbench exposes direct expert-task start')
    assert.ok(workbench.includes('startExpertTaskDirect,'), 'startExpertTaskDirect is part of Workbench public API')
    assert.ok(hub.includes("surface: state.surface === 'workbench' ? 'workbench' : 'capability'"), 'hub reports surface when starting expert')
    assert.ok(workspace.includes("drawerKind === 'capability-hub-detail'"), 'detail overlay is treated as workbench start')
    assert.ok(workspace.includes('Workbench.startExpertTaskDirect({ expertId })'), 'workbench start uses task direct path')
    assert.ok(workspace.includes("startSurface === 'workbench'"), 'workbench and capability start paths are split')
    const hubStart = workspace.indexOf("d.type === 'capability-hub-start-expert'")
    const hubStartEnd = workspace.indexOf("d.type === 'capability-hub-start-skill'", hubStart)
    const block = workspace.slice(hubStart, hubStartEnd)
    assert.ok(block.includes('startExpertTaskDirect'), 'workbench branch opens task room')
    assert.ok(block.includes('openAgentChat'), 'capability branch still opens assistant chat')
    assert.ok(block.includes('startExpertChat'), 'capability branch still creates assistant expert session')
  })

  it('quick expert card opens expert detail; new task keeps composer', () => {
    const start = workbench.indexOf('elTaskQuickGrid && elTaskQuickGrid.addEventListener')
    const end = workbench.indexOf('elTaskRecentList && elTaskRecentList.addEventListener', start)
    const quickClick = workbench.slice(start, end)
    assert.ok(quickClick.includes("openCapabilityHub('experts'"), 'quick card opens capability hub')
    assert.ok(quickClick.includes("surface: 'workbench'"), 'quick card uses workbench detail surface')
    assert.ok(quickClick.includes("presentation: 'detail'"), 'quick card opens detail-only overlay')
    assert.ok(!quickClick.includes('openTaskComposer'), 'quick card no longer opens task composer')
    assert.ok(workbench.includes("btnTaskNew && btnTaskNew.addEventListener('click', () => openTaskComposer())"), 'new task still opens composer')
    assert.ok(workspace.includes('function buildCapabilityHubSrc'), 'host builds deep-link hub URL')
    assert.ok(workspace.includes("presentation: presentation === 'detail' ? 'detail' : 'hub'"), 'host deep-link carries presentation')
    assert.ok(workspace.includes('function capabilityHubSrcMismatch'), 'host detects hub iframe src param drift')
    assert.ok(workspace.includes('reloadIfMismatch'), 'detail deep-link forces iframe reload when params differ')
    assert.ok(workspace.includes('function openCapabilityHubDetailSurface'), 'host opens transparent detail overlay')
    assert.ok(workspace.includes("drawerKind = 'capability-hub-detail'"), 'detail overlay uses dedicated drawer kind')
    assert.ok(workspace.includes('capability-hub-resume'), 'host resumes open hub with tab/expert deep link')
    assert.ok(workspace.includes('function openCapabilityHub(tab = \'experts\', opts = {})'), 'openCapabilityHub accepts options')
  })

  it('quick expert cards mirror expert-library hub-card structure', () => {
    assert.ok(workbench.includes('function renderWorkbenchQuickCard'), 'dedicated quick-card renderer')
    assert.ok(workbench.includes('wb-task-quick-head'), 'card head with avatar + title')
    assert.ok(workbench.includes('wb-task-quick-title'), 'card title matches library title slot')
    assert.ok(workbench.includes('wb-task-quick-sub'), 'card subline matches library source row')
    assert.ok(workbench.includes('wb-task-quick-desc'), 'card description matches library body')
    assert.ok(workbench.includes('wb-task-quick-badge'), 'card status badge matches library badges')
    assert.ok(workbench.includes('wb-task-quick-version'), 'card version matches library foot')
    assert.ok(workbench.includes('function expertCardTitle'), 'prefers Chinese / catalog display names')
    assert.ok(workbench.includes('agentAvatarMark(agent, \'wb-task-quick-icon\''), 'uses shared identity avatar mark')
    assert.ok(layout.includes('.wb-task-quick-icon'), 'quick card avatar styles exist')
    assert.ok(layout.includes('.wb-task-quick-badge.installed'), 'installed badge styles exist')
  })
})
