'use strict'
const { it } = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const os = require('node:os')
const { createCapabilityHubService } = require('../src/lib/capability-hub-service')
const { selectExecutionRoute } = require('../src/lib/expert-execution-profile')

it('installs the specialized Web expert and real design skills into a fresh runtime', async t => {
  const userData = fs.mkdtempSync(path.join(os.tmpdir(), 'knowme-web-expert-'))
  t.after(() => fs.rmSync(userData, { recursive: true, force: true }))
  const hub = createCapabilityHubService({ getUserData: () => userData, bundledRoot: path.resolve('src/catalog') })
  const installed = await hub.installCapability({ id: 'software-engineer', enabled: true, riskConfirmed: true })
  assert.equal(installed.ok, true, JSON.stringify(installed))
  const loaded = hub.expertRuntime().loadExpert('software-engineer')
  assert.equal(loaded.name, 'Web 开发专家')
  assert.equal(loaded.manifest.version, '3.1.0')
  for (const name of ['HTML', 'Vue', 'React', 'TypeScript']) assert.ok(loaded.systemPrompt.includes(name))
  for (const id of ['frontend-design', 'imagegen-frontend-web']) {
    assert.ok(loaded.skills.includes(id))
    const record = hub.skillRuntime().findSkillRecord(id)
    assert.ok(record, id)
    assert.equal(hub.skillRuntime().isSkillEnabled(id), true)
    const content = fs.readFileSync(path.join(userData, 'capabilities/skills', id, 'SKILL.md'), 'utf8')
    assert.ok(content.length > 3000)
  }
  const made = hub.expertRuntime().createSessionSnapshot('web-expert-check', 'software-engineer')
  assert.equal(made.ok, true)
  assert.equal(made.degraded, false, JSON.stringify(made.issues))
  assert.ok(made.snapshot.bindings.skills.includes('frontend-design'))
  const visual = selectExecutionRoute({ goal: '制作网页视觉参考' }, made.snapshot)
  assert.ok(visual.requiredSkills.includes('imagegen-frontend-web'))
  const implementation = selectExecutionRoute({ goal: '使用 Vue 和 TypeScript 实现后台表单' }, made.snapshot)
  assert.ok(implementation.requiredSkills.includes('frontend-design'))
  assert.ok(!implementation.requiredSkills.includes('imagegen-frontend-web'))
  assert.ok(loaded.capabilityManifest.permissions.tools.allowlist.includes('write_file'))
  assert.ok(loaded.capabilityManifest.permissions.tools.allowlist.includes('run_task'))
  assert.equal(loaded.capabilityManifest.permissions.write, true)
})
