/**
 * 工作台 workflow 模板区静态接线回归
 */
const { describe, it } = require('node:test')
const assert = require('node:assert')
const fs = require('node:fs')
const path = require('node:path')

const html = fs.readFileSync(path.join(__dirname, '..', 'src', 'workspace.html'), 'utf8')
const layoutCss = fs.readFileSync(path.join(__dirname, '..', 'src', 'workbench-layout.css'), 'utf8')
const consoleCss = fs.readFileSync(path.join(__dirname, '..', 'src', 'workbench-console.css'), 'utf8')
const shelfCss = fs.readFileSync(path.join(__dirname, '..', 'src', 'workbench-shelf.css'), 'utf8')
const workbenchCss = layoutCss + '\n' + consoleCss + '\n' + shelfCss
const script = fs.readFileSync(path.join(__dirname, '..', 'src', 'workbench.js'), 'utf8')
const workspace = fs.readFileSync(path.join(__dirname, '..', 'src', 'workspace.js'), 'utf8')
const main = fs.readFileSync(path.join(__dirname, '..', 'src', 'main.js'), 'utf8')
const preload = fs.readFileSync(path.join(__dirname, '..', 'src', 'preload.js'), 'utf8')
const capabilityHubService = fs.readFileSync(path.join(__dirname, '..', 'src', 'lib', 'capability-hub-service.js'), 'utf8')
const workbenchLocalStoresIpc = fs.readFileSync(path.join(__dirname, '..', 'src', 'ipc', 'workbench-local-stores.js'), 'utf8')
const workbenchLaunchIpc = fs.readFileSync(path.join(__dirname, '..', 'src', 'ipc', 'workbench-launch.js'), 'utf8')
const workbenchModeIpc = fs.readFileSync(path.join(__dirname, '..', 'src', 'ipc', 'workbench-mode.js'), 'utf8')
const workbenchAutomationIpc = fs.readFileSync(path.join(__dirname, '..', 'src', 'ipc', 'workbench-automation.js'), 'utf8')
const workbenchAuthIpc = fs.readFileSync(path.join(__dirname, '..', 'src', 'ipc', 'workbench-auth.js'), 'utf8')
const workbenchDaemonIpc = fs.readFileSync(path.join(__dirname, '..', 'src', 'ipc', 'workbench-daemon.js'), 'utf8')
const workbenchBootstrapIpc = fs.readFileSync(path.join(__dirname, '..', 'src', 'ipc', 'workbench-bootstrap.js'), 'utf8')
const workbenchLoadIpc = fs.readFileSync(path.join(__dirname, '..', 'src', 'ipc', 'workbench-load.js'), 'utf8')
const workbenchAgentGraphIpc = fs.readFileSync(path.join(__dirname, '..', 'src', 'ipc', 'workbench-agent-graph.js'), 'utf8')
const gameIpc = fs.readFileSync(path.join(__dirname, '..', 'src', 'ipc', 'game.js'), 'utf8')

describe('workbench workflow templates', () => {
  it('lands on a workflow shelf with searchable, filterable cards', () => {
    assert.match(html, /id="wbShelfSurface"[^>]*data-wb-surface="shelf"/)
    assert.match(html, /id="wbShelfSearch"/)
    assert.match(html, /id="wbShelfGrid"/)
    assert.match(html, /id="wbShelfEmpty"/)
    assert.match(html, /id="wbShelfSummary"/)
    assert.match(html, /id="wbDomainSwitcher"[\s\S]*?id="wbShelfSummary"[\s\S]*?id="wbShelfManage"/)
    assert.match(html, /class="wb-shelf-filters"[\s\S]*?id="wbShelfSummary"[\s\S]*?<\/div>\s*<div class="wb-shelf-catalog"/)
    assert.match(html, /id="wbShelfRecentList"/)
    assert.match(html, /id="wbShelfGridToggle"/)
    assert.match(html, /id="wbModeTabs"/)
    assert.doesNotMatch(html, /id="wbShelfNewWorkflow"/)
    assert.doesNotMatch(html, /id="wbSourceSwitcher"/)
    assert.doesNotMatch(html, /今天想完成什么？/)
    assert.doesNotMatch(html, /id="wbQuickGoalForm"/)
    assert.doesNotMatch(html, /id="wbModeSelect"/)
    assert.match(shelfCss, /\.wb-shelf-grid\s*\{[^}]*grid-template-columns:repeat\(2, minmax\(0, 1fr\)\)/s)
    assert.match(shelfCss, /\.wb-workflow-manage-list\s*\{[^}]*grid-template-columns:repeat\(2, minmax\(0, 1fr\)\)/s)
    assert.match(shelfCss, /\.wb-shelf-grid\.is-expanded\s*\{[^}]*max-height:min\(78vh, 720px\)/s)
    assert.match(shelfCss, /\.wb-shelf-summary:empty\s*\{\s*display:none/)
    assert.match(script, /SHELF_GRID_NARROW_MAX\s*=\s*900/)
    assert.match(script, /width <= SHELF_GRID_NARROW_MAX \? 1 : 2/)
    assert.match(script, /let shelfGridExpanded = false/)
    assert.doesNotMatch(script, /SHELF_CARD_MIN_WIDTH/)
    assert.match(shelfCss, /\.wb-shelf-outcome\s*\{[^}]*-webkit-line-clamp:2/s)
    assert.match(shelfCss, /\.wb-shelf-mark\s*\{/)
    assert.match(shelfCss, /\.wb-shelf-chips\s*\{/)
    assert.match(shelfCss, /\.wb-shelf-card h3\s*\{[^}]*font:650 14px/s)
    assert.match(shelfCss, /\.wb-shelf-card\[data-domain="office"\]/)
  })

  it('keeps task drafts and run lifecycle actions connected', () => {
    assert.match(script, /function saveTaskDraft\(/)
    assert.match(script, /terminalKind === 'failure'/)
    assert.match(workbenchLocalStoresIpc, /workbench-task-draft-save/)
    assert.match(preload, /workbenchTaskDraftSave/)
  })

  it('replaces the five-tab router with a two-surface state machine', () => {
    assert.doesNotMatch(html, /id="wbTabHome"/)
    assert.doesNotMatch(html, /id="wbTabStudio"/)
    assert.doesNotMatch(html, /id="wbTabAgents"/)
    assert.doesNotMatch(html, /id="wbTabDaemon"/)
    assert.doesNotMatch(html, /id="wbTabTasks"/)
    assert.doesNotMatch(html, /data-wb-page=/)
    assert.match(html, /id="wbShelfSurface"/)
    assert.match(html, /id="wbRunSurface"[^>]*data-wb-surface="run"/)
    assert.match(script, /function setSurface\(surface/)
    assert.match(script, /function openManagePanel\(panel\)/)
    assert.match(shelfCss, /\.wb-surface\.active\s*\{\s*display:block/)
  })

  it('does not repeat rail module branding in detail chrome', () => {
    assert.match(workbenchCss, /\.wb-head-title\s*\{\s*display:none/)
    assert.match(layoutCss, /\.app\.mode-workbench \.workbench-chat-brand\s*\{\s*display:none/)
    assert.match(layoutCss, /\.app\.mode-workbench \.agent-col-head\s*\{\s*display:none/)
    assert.match(html, /class="wb-head-tools"/)
    assert.match(html, /id="wbStartTitle"/)
  })

  it('unifies chrome brand and content-island surface with assistant', () => {
    assert.match(html, /class="app-chrome-brand"/)
    assert.match(html, /class="app-chrome-brand-title">KnowMe</)
    assert.match(html, /--content-island-radius-tl:\s*12px/)
    assert.match(html, /--content-panel-gap:\s*8px/)
    assert.match(html, /--wb-bg:\s*var\(--bg-card\)/)
    assert.match(html, /\.app\.side-collapsed \.main\s*\{[\s\S]*?border-radius:\s*var\(--content-island-radius-tl\) 0 0 0/)
    assert.match(html, /\.app:not\(\.side-collapsed\) \.sidebar\s*\{[\s\S]*?border-radius:\s*var\(--content-island-radius-tl\) var\(--content-island-radius-tl\) 0 0/)
    assert.match(html, /\.app:not\(\.side-collapsed\) \.main\s*\{[\s\S]*?border-radius:\s*var\(--content-island-radius-tl\) 0 0 0/)
    assert.match(html, /\.app:not\(\.side-collapsed\) \.main\s*\{[\s\S]*?margin-left:\s*var\(--content-panel-gap\)/)
    assert.match(html, /\.app\.mode-center-surface \.drawer\.open[\s\S]*?background:\s*var\(--bg-card\)/)
    assert.match(consoleCss, /\.workbench\s*\{[^}]*background:\s*var\(--wb-bg\)/s)
    assert.doesNotMatch(consoleCss, /radial-gradient\(circle at 46% -8%/)
    assert.doesNotMatch(layoutCss, /radial-gradient\(circle at 46% -8%/)
  })

  it('splits the workbench into task, workflow and daemon tabs', () => {
    assert.match(html, /id="wbModeTabs"[^>]*role="tablist"/)
    assert.match(html, /data-wb-mode="tasks"[^>]*>专家协作</)
    assert.match(html, /data-wb-mode="workflows"[^>]*>工作流</)
    assert.match(html, /data-wb-mode="daemon"[^>]*>管线服务</)
    assert.doesNotMatch(html, /id="wbManageToggle"/)
    assert.doesNotMatch(html, /id="wbManageMenu"/)
    assert.doesNotMatch(html, /id="wbManageClose"/)
    assert.match(script, /function syncModeTabs\(\)/)
    assert.match(script, /elShelfSearch\.hidden = activeSurface !== 'shelf'/)
    assert.match(shelfCss, /\.wb-mode-tab\.active::after/)
  })

  it('collects management surfaces into a resident manage tab', () => {
    assert.match(html, /id="wbManageSurface"[^>]*data-wb-surface="manage"/)
    assert.match(html, /data-manage-panel="workflows"/)
    assert.match(html, /data-manage-panel="daemon"/)
    assert.match(html, /data-manage-panel="automation"/)
    assert.doesNotMatch(html, /data-manage-panel="agents"/)
    assert.doesNotMatch(html, /data-manage-panel="studio"/)
    assert.doesNotMatch(html, /class="wb-manage-drawer"/)
    assert.match(html, /id="wbWorkflowManagePage"/)
    assert.match(html, /id="wbWorkflowManageList"/)
    assert.match(html, /id="wbWorkflowManageNew"/)
    assert.match(html, /id="wbWorkflowManageBack"/)
    assert.match(html, /id="wbWorkflowManageBack"[^>]*>[\s\S]*?<span>返回<\/span>/)
    assert.match(html, /class="wb-workflow-manage-title"/)
    assert.match(shelfCss, /\.wb-workflow-manage-title\s*\{/)
    assert.doesNotMatch(html, /wb-workflow-manage-tools/)
    assert.match(html, /id="wbWorkflowDeleteModal"/)
    assert.match(script, /function askWorkflowDeleteConfirm\(/)
    assert.match(script, /const DEFAULT_MANAGE_PANEL = 'workflows'/)
    assert.match(script, /function renderWorkflowManage\(\)/)
    assert.match(script, /function workflowManageItemHtml\(/)
    assert.match(script, /wb-workflow-manage-flow/)
    assert.match(script, /function workflowManageItemHtml\([\s\S]*?wb-shelf-mark/)
    assert.match(script, /data-workflow-manage="edit"/)
    assert.match(script, /data-workflow-manage="fork"/)
    assert.match(script, /data-icon="trash"/)
    assert.match(script, /workbenchWorkflowPackageArchive/)
    assert.match(shelfCss, /#wbManageSurface\.active\s*\{[^}]*display:flex/s)
    assert.match(shelfCss, /\.wb-manage-panel\.active\s*\{\s*display:block/)
    assert.match(shelfCss, /\.wb-workflow-manage-list\s*\{[^}]*grid-template-columns:repeat\(2/s)
    assert.match(shelfCss, /\.wb-workflow-manage-bottom\s*\{/)
    assert.match(shelfCss, /\.wb-workflow-manage-title\s*\{/)
    // Studio 在管理面压成两栏；管线服务为「创建管线运行 | 管线运行列表」双栏
    assert.match(shelfCss, /\.wb-manage-panel \.wb-studio-shell\s*\{[^}]*grid-template-areas:"library canvas" "library inspector"/s)
    assert.match(shelfCss, /\.wb-manage-panel \.wb-daemon-home-shell\s*\{/)
    assert.match(html, /class="wb-daemon-console"/)
    assert.match(html, /id="wbDaemonModeStatus"/)
    assert.match(html, /wb-daemon-home-shell/)
    assert.match(html, /wb-daemon-compose/)
    assert.match(html, /wb-daemon-task-rail/)
    assert.match(html, /id="wbDaemonTaskSearch"/)
    assert.match(script, /function renderDaemonMode\(\)/)
    assert.match(script, /data-daemon-action="reconnect"/)
    assert.match(script, /data-daemon-action="compose-submit"/)
    assert.match(script, /wb-daemon-compose-dropzone/)
    assert.match(script, /点击或拖拽文件到此处上传/)
    assert.match(script, /创建管线运行/)
    assert.doesNotMatch(script, /wb-daemon-compose-ingest/)
    assert.doesNotMatch(script, /minMsg \? `<p class="wb-daemon-compose-error"/)
    assert.match(script, /wb-manage-daemon/)
  })

  it('reports runnability per workflow instead of per domain', () => {
    assert.match(script, /function shelfReadiness\(item = \{\}\)/)
    assert.match(script, /item\.readiness && typeof item\.readiness === 'object'/)
    assert.match(script, /暂不可用/)
    assert.match(script, /缺少：/)
    assert.match(script, /function shelfSupplyHint\(\)/)
    assert.match(script, /data\.supply\?\.stats\?\.excluded/)
  })

  it('distinguishes workbench task command from regular Agent chat', () => {
    assert.match(html, /workbench-chat-brand/)
    assert.match(html, /任务协作/)
    assert.match(html, /首页/)
    assert.match(html, /工作流/)
    assert.match(html, /id="wbRunStatus"/)
    assert.match(html, /workbench-task-brief\.js/)
    assert.match(script, /wb-task-state-dot/)
    assert.match(script, /factualBrief/)
    assert.match(script, /localWaiting/)
    assert.match(workspace, /setSurfaceMode\(workbenchOn \? 'workbench' : 'agent'\)/)
    assert.match(workspace, /WorkspaceAgent\.setSurfaceMode/)
    const agentScript = fs.readFileSync(path.join(__dirname, '..', 'src', 'workspace-agent.js'), 'utf8')
    assert.match(agentScript, /function setSurfaceMode\(mode\)/)
    assert.match(agentScript, /SURFACE_SESSION_KEY/)
    assert.match(agentScript, /WORKBENCH_SESSION_GOAL/)
    assert.match(agentScript, /activateSurfaceSession\(surfaceMode\)/)
    assert.match(agentScript, /function enterWorkbenchTask\(context/)
    assert.match(agentScript, /工作台任务上下文/)
    assert.match(agentScript, /任务事实门禁/)
    assert.match(agentScript, /补充任务要求或材料… @ 选文件/)
    assert.match(agentScript, /syncDaemonHitlFromContext/)
    assert.match(agentScript, /daemon-hitl/)
    assert.match(agentScript, /submitDaemonClarificationAnswer/)
    assert.match(agentScript, /workbenchDaemonClarify/)
    assert.match(agentScript, /data-daemon-hitl-decision/)
    assert.match(agentScript, /isWorkbenchOwnedSession/)
    assert.match(agentScript, /relocateWorkbenchSessionsFromAgentSurface/)
    assert.match(agentScript, /\/\^工作台\\s\*\[·\\-—–\]/)
    assert.match(workspace, /openAgentChat[\s\S]*setWorkbenchTaskView\(false\)/)
    assert.match(workspace, /expert-chat', 'workflow-chat'/)
    assert.match(workspace, /勿再套一层/)
  })

  it('uses a full-width home and opens a task-scoped conversation workspace', () => {
    assert.match(layoutCss, /\.app\.mode-workbench \.agent-col\s*\{\s*display:none/)
    assert.match(html, /\.agent-col\s*\{[^}]*flex:1 1 0/s)
    assert.match(html, /\.pane-wrap\s*\{[^}]*flex:1 1 0/s)
    assert.match(html, /workbench-layout\.css\?v=\d+/)
    assert.match(html, /workbench-console\.css\?v=\d+/)
    assert.match(layoutCss, /\.app\.mode-workbench\[data-workbench-layout="task-room"\] \.main,[\s\S]*display:\s*grid;/)
    assert.match(layoutCss, /\.app\.mode-workbench\[data-workbench-layout="task-room"\] \.main,[\s\S]*grid-template-columns:\s*minmax\(0, 1fr\) clamp\(420px, 48%, 640px\);/)
    assert.match(layoutCss, /\.app\.mode-workbench\[data-workbench-layout="task-room"\] \.agent-col,[\s\S]*grid-column:\s*1;[\s\S]*grid-row:\s*2;/)
    assert.match(layoutCss, /\.app\.mode-workbench\[data-workbench-layout="task-room"\] #workSurfaceWrap,[\s\S]*grid-column:\s*2;[\s\S]*grid-row:\s*2;/)
    assert.match(layoutCss, /\[data-workbench-task-kind="expert-chat"\] \.main,[\s\S]*grid-template-columns:\s*minmax\(0, 1fr\) clamp\(280px, 34%, 400px\);/)
    assert.match(layoutCss, /\.agent-dialogue-status-bar:not\(\[hidden\]\),[\s\S]*grid-column:\s*1 \/ -1;/)
    assert.match(layoutCss, /\.agent-dialogue-status-bar[\s\S]*height:\s*52px;/)
    assert.match(layoutCss, /\[data-workbench-layout="task-room"\] \.wb-run-topbar,[\s\S]*display:\s*none !important;/)
    assert.match(html, /id="agentDialogueStatusMode"/)
    assert.match(script, /mode: '协作'/)
    assert.match(script, /mode: modeFromOrigin === '管线服务' \? '管线服务' : '工作流'/)
    assert.match(script, /foldDialogueStatusTitle/)
    assert.match(script, /function dialogueModeFromOrigin\(/)
    assert.match(script, /if \(run\.mode === 'daemon'\) return '管线服务'/)
    assert.match(script, /\$\{title\} · \$\{meta\}/)
    assert.match(
      layoutCss,
      /\.app\.mode-workbench\[data-workbench-layout="task-room"\] \.agent-chat-log,[\s\S]*--agent-message-track:\s*min\(1080px, 100%\);[\s\S]*width:\s*100%;[\s\S]*align-self:\s*stretch;/,
      'task-room chat fills the dialogue column instead of the centered 980 track'
    )
    assert.match(
      layoutCss,
      /\.app\.mode-workbench\[data-workbench-layout="task-room"\] \.agent-chat-log,[\s\S]*--agent-reading-track:\s*min\(1080px, 100%\);/,
      'task-room reading track matches the widened message track'
    )
    assert.match(html, /\.app\.mode-agent:not\(\.agent-has-document\) \.agent-chat-log,[\s\S]*?width:min\(980px, calc\(100% - 64px\)\)/)
    assert.match(workspace, /shell\.dataset\.workbenchTaskKind/)
    assert.doesNotMatch(html, /:has\(#wbRunner:not\(\[hidden\]\)\) \.agent-col/, 'runner state must not reopen chat on the home page')
    assert.match(workspace, /function setWorkbenchTaskView\(active, context/)
    assert.match(workspace, /meta = \{\}/)
    assert.match(workspace, /shell\.dataset\.workbenchLayout = taskRoom \? 'task-room' : 'overview'/)
    assert.match(workspace, /workbench-task-active/)
    assert.match(workspace, /onViewChange: setWorkbenchTaskView/)
    assert.match(workspace, /function openAgentChat\(\)/)
    assert.match(workspace, /workbenchOn = false/)
    assert.match(script, /onViewChange\(active, active \? workbenchTaskContext\(\) : \{\}, \{/)
    assert.match(script, /setWorkbenchPage\('tasks', \{ force: true \}\)/)
    assert.match(script, /run\.intent = goal/)
    assert.match(script, /run\.intent = \(item && item\.intent\)/)
  })

  it('styles run artifact rows in the console overlay', () => {
    assert.match(consoleCss, /\.wb-run-artifact-row\s*\{/)
    assert.match(consoleCss, /\.wb-run-artifact-label\s*\{/)
    assert.match(consoleCss, /\.wb-run-artifact-reuse\s*\{/)
    assert.match(consoleCss, /\.wb-dag-summary\.is-loading/)
    assert.match(consoleCss, /\.wb-run-status\.tone-error/)
  })

  it('shows a business workflow graph in the task context rail', () => {
    assert.match(html, /id="wbRunStatus"/)
    assert.match(html, /id="wbRunProgress"/)
    assert.match(html, /你现在要做什么/)
    assert.match(html, /id="wbRunNextAction"/)
    assert.match(html, /id="wbRunGoal"/)
    assert.match(html, /id="wbRunAgents"/)
    assert.match(html, /id="wbRunGraph"/)
    assert.match(html, /id="wbRunArtifacts"/)
    assert.match(workbenchCss, /\.wb-graph-node\.active/)
    assert.match(workbenchCss, /\.wb-run-agent\.is-active/)
    assert.match(script, /function graphNodes\(\)/)
    assert.match(script, /function renderTaskContext\(\)/)
    assert.match(script, /function applyTaskProjection\(/)
    assert.match(script, /run\.projection\.graphNodes/)
    assert.doesNotMatch(script, /目标与材料/)
    assert.doesNotMatch(script, /AgentTeams 协作/)
    assert.doesNotMatch(script, /结果与交付/)
  })

  it('hydrates daemon tasks via workbench-task-projection IPC', () => {
    const projection = fs.readFileSync(path.join(__dirname, '..', 'src', 'lib', 'workbench-task-projection.js'), 'utf8')
    assert.match(projection, /function projectTaskRoom\(/)
    assert.match(main, /workbenchTaskProjection\.projectTaskRoom/)
    assert.match(workbenchDaemonIpc, /projection: projectDaemonTask\(raw, daemonRepo\)/)
    assert.match(workbenchDaemonIpc, /resolveDaemonContentRepo/)
    assert.match(workbenchDaemonIpc, /workbench-daemon-artifact-open/)
    assert.match(preload, /workbenchDaemonArtifactOpen/)
    assert.match(script, /workbenchDaemonArtifactOpen/)
    assert.match(script, /currentOwner/)
    assert.match(script, /degradedReason/)
    assert.match(script, /无法确认进度/)
    assert.match(script, /degradedPlaceholder/)
    assert.match(script, /open-sources/)
    assert.match(script, /该产物尚未生成或未同步/)
    assert.match(workbenchDaemonIpc, /resolveArtifactOpenPath/)
  })

  it('separates workflow orchestration and Daemon responsibilities', () => {
    assert.match(html, /id="wbStudioSurface"/)
    assert.match(html, /id="wbDaemonPage"/)
    assert.match(html, /id="wbDaemonModeList"/)
    assert.ok(html.indexOf('id="wbManageSurface"') < html.indexOf('id="wbRunSurface"'))
    assert.doesNotMatch(html, /id="wbAgentManagerList"/)
    assert.match(script, /function renderDaemonMode\(/)
  })

  it('presents the workbench entrance as a workflow shelf', () => {
    assert.match(html, /placeholder="搜索想要的结果"/)
    assert.match(html, /id="wbShelfLocked"/)
    assert.doesNotMatch(html, /class="wb-console-overview[\s"]/)
    assert.doesNotMatch(html, /需要你处理/)
    assert.doesNotMatch(html, /准备情况与需要连接的能力/)
    assert.doesNotMatch(html, /\.wb-agent-card:nth-child/)
    // 顶栏副标题不再复述 hero 计数，也不暴露内容来源仓库名
    assert.match(script, /if \(elHeadSub\) elHeadSub\.textContent = ''/)
    assert.doesNotMatch(script, /本机服务在线/)
  })

  it('provides an editable local-Agent workflow with managed capability settings', () => {
    assert.match(html, /id="wbStudioPalette"/)
    assert.match(html, /id="wbStudioGraph"[^>]*data-studio-dropzone="true"/)
    assert.doesNotMatch(html, /id="wbStudioAddAgent"/)
    assert.doesNotMatch(html, /data-studio-lib-tab="config"/)
    assert.doesNotMatch(html, /id="wbStudioAgents"/)
    assert.match(html, /节点属性/)
    assert.match(script, /WorkbenchStudioModel\.addAgent/)
    assert.match(script, /WorkbenchStudioCanvas\.buildBoard|function renderStudioBoardGraph/)
    assert.match(script, /function openStudioExpertPicker/)
    assert.match(script, /wb-studio-expert-picker-library/)
    assert.match(script, /workbenchQuickExperts/)
    assert.match(script, /data-studio-relation/)
    assert.match(script, /接着执行/)
    assert.match(script, /同时执行/)
    assert.match(script, /执行前确认/)
    assert.match(script, /data-studio-field="intent"/)
    assert.match(script, /data-studio-field="role"/)
    assert.match(script, /data-studio-tune-agent/)
    assert.match(script, /function openOrchestration\(/)
    assert.doesNotMatch(script, /data-studio-manage-agent/)
    assert.doesNotMatch(script, /data-studio-save-agent/)
    assert.match(script, /function saveStudioWorkflow\(/)
    assert.match(consoleCss, /\.wb-studio-graph\.is-dragover/)
    assert.match(consoleCss, /\.wb-studio-flow-node/)
    assert.match(consoleCss, /\.wb-studio-edge/)
  })

  it('keeps the run surface visible while the shelf is suspended in task room', () => {
    assert.match(layoutCss, /#workbench\[data-layout="task-room"\] #wbShelfSurface\s*\{\s*display:\s*none !important/)
    assert.match(layoutCss, /#workbench\[data-layout="task-room"\] #wbRunSurface\s*\{\s*display:\s*flex !important/)
    assert.match(script, /setSurface\('run', \{ force: true \}\)/)
  })

  it('flattens daemon review chrome and opens code workspace browser', () => {
    assert.doesNotMatch(html, /审阅 制品/)
    assert.doesNotMatch(html, /wb-daemon-review-title/)
    assert.match(layoutCss, /\.wb-runner\.is-daemon-review \.wb-runner-head\s*\{[^}]*display:\s*none/s)
    assert.doesNotMatch(shelfCss, /linear-gradient\(180deg,\s*#f6f5f1/)
    assert.match(shelfCss, /\.wb-run-shell:has\(\.wb-runner\.is-daemon-review\) \.wb-run-body/)
    assert.match(layoutCss, /\.wb-daemon-review-progress-bar/)
    assert.match(layoutCss, /\.wb-ws-modal/)
    assert.match(html, /id="wbDaemonWorkspaceMask"/)
    assert.match(html, /class="wb-modal-mask wb-ws-mask"/)
    assert.match(layoutCss, /\.wb-ws-mask/)
    assert.match(layoutCss, /\.wb-ws-modal/)
    assert.match(script, /function openDaemonWorkspaceBrowser\(/)
    assert.match(script, /workbenchDaemonWorkspaceTree/)
    assert.match(script, /includeChanges: true, light: true/)
    assert.doesNotMatch(script, /actionButton\('restart-task', '重跑'/)
    assert.match(html, /id="wbDaemonReviewRefresh"[^>]*data-run-action="refresh-task"/)
    assert.match(html, /class="wb-daemon-review-refresh"[^>]*id="wbDaemonReviewRefresh"/)
    assert.match(html, /id="wbDaemonReviewIdentity"/)
    assert.match(html, /id="wbDaemonReviewWorkflowName"/)
    assert.match(layoutCss, /\.wb-daemon-review-identity\s*\{/)
    assert.match(script, /wbDaemonReviewIdentity/)
    assert.match(script, /meta = ''/)
    assert.match(html, /data-review-tab="logs"/)
    assert.doesNotMatch(html, /data-run-action="focus-process-logs"/)
    assert.doesNotMatch(html, /class="wb-daemon-review-foot"/)
    assert.match(layoutCss, /\.wb-daemon-review-refresh\s*\{[^}]*margin-left:\s*auto/s)
    assert.match(layoutCss, /\.wb-daemon-review-logs\s*\{/)
    assert.match(layoutCss, /\.wb-daemon-progress-md\s*\{/)
    assert.match(layoutCss, /\.wb-daemon-review-logs-block\.is-collapsed/)
    assert.match(script, /data-logs-toggle/)
    assert.doesNotMatch(script, /daemonProgressViewMode/)
    assert.doesNotMatch(script, /data-progress-view/)
    assert.doesNotMatch(script, /wb-daemon-review-logs-fold/)
    assert.match(script, /MarkdownLite\.render/)
    assert.match(script, /title: '全部过程'|title: \"全部过程\"/)
    assert.match(script, /data-progress-preview/)
    assert.match(script, /openDaemonProgressPreview/)
    assert.doesNotMatch(script, /enhanceDaemonProgressMdTables|data-md-table-preview/)
    assert.match(layoutCss, /\.wb-daemon-progress-preview\s*\{/)
    assert.match(layoutCss, /\.wb-daemon-progress-preview-modal/)
    assert.doesNotMatch(layoutCss, /\.wb-daemon-md-table-preview/)
    assert.doesNotMatch(layoutCss, /\.wb-daemon-md-section-head/)
    assert.match(layoutCss, /data-logs-block="progress"\]:not\(\.is-collapsed\)/)
    assert.match(html, /markdown-lite\.js/)
    assert.match(layoutCss, /\.wb-runner\.is-daemon-review \.wb-runner-actions\[hidden\]/)
    assert.match(script, /reviewRefresh\.hidden = !run\.slug/)
    assert.match(script, /elRunnerActions\.hidden = !actions/)
    assert.match(script, /switchDaemonReviewTab\('logs'\)/)
    assert.match(script, /setDaemonProcessFeed\(null\)/)
    assert.match(script, /projectChatProgressCard/)
    assert.match(script, /kind === 'chat-progress'|compact:\s*true/)
    assert.doesNotMatch(script, /actionButton\('back', '返回', '', \{ icon: 'chevronLeft'/)
    assert.doesNotMatch(script, /代码工作区将在后续接入 Daemon workspace API/)
    assert.match(script, /elRecentNote\.hidden = !note/)
  })

  it('aligns daemon chat progress, hitl questions, and artifact rows with webui', () => {
    const agentScript = fs.readFileSync(path.join(__dirname, '..', 'src', 'workspace-agent.js'), 'utf8')
    assert.match(script, /function syncDaemonProcessFeed\(/)
    assert.match(script, /projectChatProgressCard\(/)
    assert.match(agentScript, /管线进度/)
    assert.match(agentScript, /data-daemon-open-logs/)
    assert.doesNotMatch(agentScript, /agent-daemon-progress-kicker/)
    assert.match(agentScript, /agent-daemon-progress-card/)
    assert.match(agentScript, /agent-daemon-hitl-questions/)
    assert.match(agentScript, /data-daemon-hitl-input/)
    assert.match(agentScript, /提交答复/)
    assert.match(script, /wb-daemon-review-artifact is-webui/)
    assert.match(script, /wb-daemon-review-artifact-preview/)
    assert.match(script, /wb-daemon-review-artifact-name/)
    assert.match(script, /wb-daemon-review-artifact-meta/)
    assert.match(script, /wb-daemon-review-artifact-icon/)
    assert.match(layoutCss, /\.wb-daemon-review-artifact\.is-webui/)
    assert.match(html, /\.agent-daemon-progress-card/)
  })

  it('fills result stage flat and rows icon footer actions without shelf back', () => {
    assert.match(shelfCss, /\.wb-run-stage\[data-run-stage="result"\]\s*\{[^}]*justify-content:\s*flex-start/s)
    assert.match(shelfCss, /\.wb-run-stage\[data-run-stage="result"\]\s+\.wb-run-stage-inner\s*\{[^}]*flex:\s*1/s)
    assert.match(shelfCss, /\.wb-run-stage\[data-run-stage="result"\]\s+\.wb-run-stage-inner\s*\{[^}]*background:\s*transparent/s)
    assert.match(shelfCss, /\.wb-run-stage\[data-run-stage="result"\]\s+\.wb-run-stage-inner\s*\{[^}]*box-shadow:\s*none/s)
    assert.match(shelfCss, /\.wb-run-result-list\s*\{[^}]*border-radius:\s*8px/s)
    assert.match(shelfCss, /\.wb-run-result-item\s*\{[^}]*flex-direction:\s*row/s)
    assert.match(shelfCss, /\.wb-run-result-body\s*\{[^}]*flex:\s*1/s)
    assert.match(shelfCss, /\.wb-run-result-actions\s*\{[^}]*margin-top:\s*auto/s)
    assert.doesNotMatch(shelfCss, /\.wb-run-result-actions\s*\{[^}]*flex-direction:\s*column/s)
    assert.doesNotMatch(script, /data-run-result="back"/)
    assert.match(script, /data-run-result="again"><span class="ico" data-icon="refresh"/)
    assert.match(script, /data-run-result="log"><span class="ico" data-icon="history"/)
    assert.match(script, /该产物尚未生成或未同步/)
    assert.match(script, /function openDaemonArtifactPath\(/)
    assert.match(script, /function isDaemonInputArtifactPath\(/)
    assert.match(script, /isDaemonInputArtifactPath\(pathValue\)/)
    assert.match(script, /action === 'again'\)[\s\S]{0,200}setRunStage\('running'\)/)
    assert.match(script, /setRunStage\('running'\)[\s\S]{0,120}focusDaemonProcessLogs\(/)
    assert.match(workbenchDaemonIpc, /downloadArtifact/)
    assert.match(workbenchDaemonIpc, /materializeDaemonArtifact/)
    assert.match(script, /function backDaemonRunToPipelineTasks\(/)
    assert.match(script, /function dialogueModeFromOrigin\(/)
    assert.match(script, /btnRunBack && btnRunBack\.addEventListener\('click', \(\) => \{\s*leaveDialogueTaskRoom\(\)/)
    assert.match(script, /run\.mode === 'daemon' \? 'daemon'/)
    assert.match(script, /surface: 'daemon'/)
    // 返回按来源恢复，禁止凡 daemon 一律硬跳管线
    assert.doesNotMatch(script, /if \(run\.mode === 'daemon'\) \{\s*void backDaemonRunToPipelineTasks\(\)/)
  })

  it('restores dialogue back navigation to the origin category home', () => {
    assert.match(script, /function resolveReturnSurface\(/)
    assert.match(script, /function restoreTaskRoomReturnState\(/)
    assert.match(script, /target === 'daemon'\) openManagePanel\('daemon'\)/)
    assert.match(script, /target === 'shelf'\) setSurface\('shelf'/)
    assert.match(script, /setSurface\('taskhome'/)
    assert.match(script, /function leaveDialogueTaskRoom\(/)
    assert.match(script, /void backToRunList\(\)/)
    // 工作流货架启动的 daemon 跑批须保留 shelf 来源，不得因 mode=daemon 改道
    assert.match(script, /origin !== 'daemon'/)
    assert.match(script, /dialogueModeFromOrigin\(\)/)
  })

  it('runs a three-stage flow: confirm inputs, execute, deliver artifacts', () => {
    assert.match(html, /id="wbRunStageInput"[^>]*data-run-stage="input"/)
    assert.match(html, /id="wbRunStageLive"[^>]*data-run-stage="running"/)
    assert.match(html, /id="wbRunStageResult"[^>]*data-run-stage="result"/)
    assert.doesNotMatch(html, /id="wbRunStepper"/)
    assert.match(html, /id="wbHead"/)
    assert.match(html, /id="wbRunBack"/)
    assert.match(html, /id="wbRunInputForm"/)
    assert.match(html, /id="wbRunBackendNote"/)
    assert.match(html, /id="wbRunInputAgents"/)
    assert.match(html, /class="wb-run-stage-badge"/)
    assert.match(html, /id="wbRunOutcome"/)
    assert.match(html, /id="wbRunBack"[^>]*>[\s\S]*?返回/)
    assert.doesNotMatch(html, /wb-run-topbar[\s\S]{0,500}确认输入/)
    assert.doesNotMatch(html, /wb-run-topbar[\s\S]{0,500}data-run-step/)
    assert.match(script, /function setRunStage\(stage\)/)
    assert.match(script, /function syncRunOutcomePill\(/)
    assert.match(script, /function runOutcomePresentation\(/)
    assert.match(script, /HITL[\s\S]{0,80}等待优先于完成|等待优先于完成/)
    assert.match(script, /label: '等待你'[\s\S]{0,400}label: '已完成'/)
    assert.match(script, /function runNodeProgressMeta\(/)
    assert.match(script, /btnRunBack/)
    assert.match(script, /hideGlobalHead = activeSurface === 'run'/)
    assert.match(script, /showBack = activeSurface === 'studio'/)
    assert.match(script, /function syncDialogueStatusBar\(/)
    assert.match(script, /function leaveDialogueTaskRoom\(/)
    assert.match(html, /id="agentDialogueStatusBar"/)
    assert.match(html, /id="agentDialogueStatusTitle"/)
    assert.match(html, /id="agentDialogueStatusBack"/)
    assert.match(html, /id="wbExpertTaskTitle"/)
    assert.doesNotMatch(script, /showBack = activeSurface === 'studio'[\s\S]{0,120}activeSurface === 'run' && !!run\.workflow/)
    assert.match(script, /function renderRunInputStage\(\)/)
    assert.match(script, /function renderRunResultStage\(\)/)
    assert.doesNotMatch(html, /id="wbRunResultTitle"/)
    assert.doesNotMatch(script, /任务已完成 · /)
    assert.match(script, /function runResultIdentity\(/)
    assert.match(script, /run\.mode === 'daemon'[\s\S]{0,180}kicker:\s*'管线'/)
    assert.match(script, /daemonRunIdentityTitle\(\)/)
    assert.match(script, /wb-run-result-block/)
    assert.match(script, /wb-run-result-kicker/)
    assert.match(script, /wb-run-result-title/)
    assert.match(script, /wb-run-result-section-title/)
    assert.match(script, /产物（\$\{artifactCount\}）/)
    assert.match(shelfCss, /\.wb-run-result-block\s*\{[^}]*border-bottom:\s*1px\s+solid\s+var\(--wb-border/s)
    assert.match(shelfCss, /\.wb-run-result-kicker\s*\{/)
    assert.match(shelfCss, /\.wb-run-result-title\s*\{[^}]*font:\s*680\s+16px/s)
    assert.match(shelfCss, /\.wb-run-result-section-title\s*\{[^}]*--wb-text/s)
    assert.doesNotMatch(shelfCss, /\.wb-run-result-section-title\s*\{[^}]*--wb-text-muted/s)
    assert.match(layoutCss, /\.wb-side-workflow-name\s*\{[^}]*--wb-text/s)
    assert.match(script, /resultSummary/)
    assert.match(script, /Object\.values\(value\.nodes \|\| \{\}\)/)
    assert.match(workbenchAgentGraphIpc, /agentArtifactTools\.listArtifacts\(undefined, runId\)/)
    assert.match(script, /async function confirmRunInputs\(\)/)
    assert.match(script, /执行方式：\$\{backend\}（系统自动选择）/)
    assert.match(script, /wb-run-field-req/)
    assert.match(script, /填写本次信息/)
    assert.match(script, /本机专家团队/)
    assert.match(script, /wb-daemon-review-progress/)
    assert.doesNotMatch(script, /wb-daemon-review-progress-title/)
    assert.doesNotMatch(html, /wbDaemonReviewRec|推荐查看/)
    assert.doesNotMatch(html, /wb-daemon-review-meta/)
    assert.doesNotMatch(script, /elDaemonReviewRec/)
    assert.doesNotMatch(layoutCss, /\.wb-daemon-review-progress-title|\.wb-daemon-review-rec/)
    assert.match(script, /wb-daemon-review-step-output/)
    assert.match(script, /wb-daemon-review-step-card/)
    assert.match(script, /wb-daemon-review-step-head/)
    assert.match(script, /wb-daemon-review-step-body/)
    assert.match(script, /wb-daemon-review-steps is-zigzag/)
    assert.match(script, /is-zig-left/)
    assert.match(script, /is-zig-right/)
    assert.match(script, /function stepCardTitles\(/)
    assert.match(script, /wb-daemon-review-step-en/)
    assert.match(script, /data-step-id/)
    assert.match(script, /data-step-detail-back/)
    assert.match(script, /wb-daemon-review-step-close/)
    assert.match(script, /data-icon="close"/)
    assert.doesNotMatch(script, /返回步骤/)
    assert.match(script, /daemonReviewStepId/)
    assert.match(script, /renderDaemonStepDetail/)
    assert.match(layoutCss, /\.wb-daemon-review-step-close/)
    assert.match(script, /step\.outputLabel/)
    assert.match(layoutCss, /\.wb-daemon-review-step-output/)
    assert.match(layoutCss, /\.wb-daemon-review-step-card/)
    assert.match(layoutCss, /\.wb-daemon-review-step-head/)
    assert.match(layoutCss, /\.wb-daemon-review-step-body/)
    assert.match(layoutCss, /\.wb-daemon-review-steps\.is-zigzag/)
    assert.match(layoutCss, /\.is-zig-right\s*\{\s*margin-top:\s*-16px/)
    assert.match(layoutCss, /\.wb-daemon-review-step-card::after/)
    assert.match(layoutCss, /\.wb-daemon-review-step-detail/)
    assert.match(layoutCss, /text-overflow:\s*ellipsis/)
    assert.doesNotMatch(script, /Local Team Runtime/)
    const agentScript = fs.readFileSync(path.join(__dirname, '..', 'src', 'workspace-agent.js'), 'utf8')
    assert.match(agentScript, /chatLog\.appendChild\(feed\)/)
    assert.doesNotMatch(agentScript, /chatLog\.prepend\(feed\)/)
    assert.match(agentScript, /scrollDaemonProcessLogToLatest/)
    assert.match(agentScript, /全文日志仍在右侧「过程日志」Tab/)
    assert.match(layoutCss, /\.agent-daemon-process\s*\{[^}]*margin:\s*10px 0 0/s)
    assert.doesNotMatch(
      script.slice(script.indexOf('function renderRunInputStage'), script.indexOf('function renderRunResultStage')),
      /field\.type \? ` <small>/,
    )
    assert.match(shelfCss, /\.wb-run-outcome/)
    assert.match(shelfCss, /\.wb-run-outcome\.tone-error/)
    assert.match(shelfCss, /\.wb-run-topbar-meta/)
    assert.doesNotMatch(html, /wb-daemon-review-badge/)
    assert.doesNotMatch(html, /data-review-badge/)
  })

  it('keeps grounding facts out of the completed collaboration empty state', () => {
    const agentScript = fs.readFileSync(path.join(__dirname, '..', 'src', 'workspace-agent.js'), 'utf8')
    assert.match(agentScript, /agent-empty-workbench is-completed/)
    assert.match(agentScript, /已完成 · 无可打开产物/)
    assert.doesNotMatch(agentScript, /split\('\\n'\)\.slice\(0, 4\).*tip-label">事实/)
  })

  it('gives workbench Agent Graph nodes an artifact-capable tool surface', () => {
    const factory = main.slice(
      main.indexOf('function createWorkbenchAgentPortFactory'),
      main.indexOf('const SOURCES_FILE'),
    )
    assert.match(factory, /agentArtifactTools\.buildArtifactTools\(\{ runId: childRunId \}\)/)
    assert.match(factory, /resolveToolSurfaceForRun\(\{/)
    assert.match(factory, /connectorToolRuntime\.buildConnectorToolSurface/)
    assert.match(factory, /必须调用 create_artifact 保存产物/)
    assert.match(factory, /childPorts\._dispose = resolvedSurface\.close/)
  })

  it('routes agent authoring to capability hub instead of manage drawer', () => {
    assert.doesNotMatch(html, /id="wbAgentManagerList"/)
    assert.doesNotMatch(html, /id="wbAgentManagerForm"/)
    assert.match(script, /function openCapabilityPicker\(/)
    assert.match(script, /openCapabilityPicker\('experts'\)/)
    assert.doesNotMatch(script, /function renderAgentManager\(\)/)
  })

  it('does not allow agent profile editing from workbench modals', () => {
    assert.doesNotMatch(script, /配置 Profile/)
    assert.doesNotMatch(script, /kind === 'agent-profile'/)
    assert.doesNotMatch(script, /openAgentProfile/)
    assert.doesNotMatch(script, /wbAgentProfileSkills/)
    assert.doesNotMatch(script, /agentProfileSave/)
    assert.match(script, /data-agent-tune-capability/)
    assert.match(script, /前往专家库调优专家/)
  })

  it('keeps console shell selectors authoritative in workbench-console.css', () => {
    assert.match(consoleCss, /\.wb-head\s*\{/)
    assert.match(consoleCss, /\.wb-body\s*\{/)
    // 货架 / 运行 / 管理三块样式集中在 workbench-shelf.css，不散落到 layout
    assert.match(shelfCss, /\.wb-shelf\s*\{/)
    assert.match(shelfCss, /\.wb-run-shell\s*\{/)
    assert.match(shelfCss, /\.wb-manage-head\s*\{/)
    assert.doesNotMatch(layoutCss, /\.wb-shelf-card\s*\{/)
    assert.doesNotMatch(consoleCss, /\.wb-shelf-card\s*\{/)
    // 编排顶栏图标按钮锁定同一正方形尺寸
    assert.match(consoleCss, /\.wb-studio-tool-btn\s*\{[^}]*flex:\s*0 0 30px/s)
    assert.match(consoleCss, /\.wb-studio-tool-btn\s*\{[^}]*width:\s*30px/s)
    assert.match(consoleCss, /\.wb-studio-tool-btn\s*\{[^}]*height:\s*30px/s)
    assert.match(consoleCss, /\.wb-studio-tool-btn \.ico\s*\{[^}]*width:\s*15px/s)
  })

  it('allows only one primary action in task detail surfaces', () => {
    assert.match(script, /function runnerDegradedDetailActive\(\)/)
    assert.match(script, /const primaryBlocked = runnerDegradedDetailActive\(\) && kind === 'primary'/)
    assert.match(script, /let gatePrimaryUsed = false/)
    assert.match(script, /const primary = !gatePrimaryUsed \? 'primary' : ''/)
  })

  it('maps cancelled, degraded and permission run semantics in task context', () => {
    assert.match(script, /tone = 'cancelled'/)
    assert.match(script, /is-permission/)
    assert.match(script, /is-degraded/)
    assert.match(consoleCss, /\.wb-run-status\.tone-cancelled/)
    assert.match(consoleCss, /\.wb-run-status\.is-permission/)
  })

  it('shows expert profiles with user-facing capability tags and opens their detail view', () => {
    assert.match(script, /function chineseRoleName\(agent\)/)
    assert.match(script, /function englishAgentName\(agent\)/)
    assert.match(script, /function roleIconName\(agent\)/)
    assert.match(script, /function agentAvatarMark\(/)
    assert.match(script, /function agentCapabilities\(agent\)/)
    assert.match(script, /function openAgentDetail\(id\)/)
  })

  it('keeps expert descriptions free of internal developer jargon', () => {
    const presenter = fs.readFileSync(path.join(__dirname, '..', 'src', 'lib', 'workbench-presenter.js'), 'utf8')
    assert.match(presenter, /INTERNAL_PATTERNS/)
    assert.match(presenter, /function userFacingSummary\(/)
    assert.match(presenter, /function capabilityTags\(/)
    assert.match(html, /lib\/workbench-presenter\.js/)
    assert.match(script, /function agentSummary\(/)
    assert.match(script, /function agentCapabilities\(/)
    const model = fs.readFileSync(path.join(__dirname, '..', 'src', 'lib', 'workbench-model.js'), 'utf8')
    assert.match(model, /function normalizeDisplay\(/)
  })

  it('renders expert details through the existing secondary modal', () => {
    assert.match(script, /modal\.kind === 'agent'/)
    assert.match(script, /wb-agent-detail-hero/)
    assert.match(script, /agentAvatarMark\(agent, 'wb-agent-detail-avatar'/)
    assert.match(script, /agentSummary\(agent, role\)/)
    assert.match(script, /由工作流按需调度/)
    assert.match(script, /btnModalConfirm\) btnModalConfirm\.hidden = true/)
  })

  it('drops the primary/advanced workflow catalog in favour of one shelf', () => {
    assert.doesNotMatch(html, /id="wbWorkflowSections"/)
    assert.doesNotMatch(html, /id="wbWorkflowBrowser"/)
    assert.doesNotMatch(html, /id="wbWorkflowAdvancedSection"/)
    assert.doesNotMatch(script, /function renderWorkflowCard\(/)
    assert.doesNotMatch(script, /function categorizeWorkflows\(/)
    assert.match(script, /function shelfItems\(\)/)
    assert.match(script, /function shelfCardHtml\(item\)/)
  })

  it('omits the header running popover in favour of task and pipeline surfaces', () => {
    assert.doesNotMatch(html, /id="wbRunningToggle"/)
    assert.doesNotMatch(html, /id="wbRunningPopover"/)
    assert.doesNotMatch(html, /id="wbTaskList"/)
    assert.doesNotMatch(script, /function renderRunList\(\)/)
    assert.doesNotMatch(script, /function runningToggleAllowedOnSurface\(\)/)
    assert.doesNotMatch(script, /function syncRunningToggleVisibility\(/)
    assert.match(html, /id="wbTaskRecentList"/)
    assert.match(html, /id="wbShelfRecentList"/)
    assert.match(html, /id="wbShelfRecentEmpty"/)
    assert.match(html, /id="wbShelfTaskManage"/)
    assert.match(html, /id="wbShelfGridToggle"/)
    assert.match(html, /工作流运行/)
    assert.match(script, /function paintShelfRecentList\(/)
    assert.match(script, /function paintShelfGrid\(/)
    assert.match(script, /function shelfRowCapacity\(/)
    assert.match(script, /function workflowShelfTasks\(/)
    assert.match(html, /id="wbDaemonRunFilters"/)
  })

  it('clears task-room layout before painting shelf grid on return', () => {
    const setSurfaceMatch = script.match(/function setSurface\(surface, \{ force = false \} = \{\}\) \{[\s\S]*?\n  \}/)
    assert.ok(setSurfaceMatch, 'setSurface present')
    const setSurfaceBody = setSurfaceMatch[0]
    const pageChangeAt = setSurfaceBody.indexOf('onPageChange(activePage)')
    const renderShelfAt = setSurfaceBody.indexOf('renderShelf()')
    assert.ok(pageChangeAt >= 0 && renderShelfAt >= 0, 'onPageChange and renderShelf in setSurface')
    assert.ok(pageChangeAt < renderShelfAt, 'onPageChange must run before renderShelf')
    assert.match(setSurfaceBody, /requestAnimationFrame\(\(\) => \{\s*if \(activeSurface === 'shelf'\) paintShelfGrid\(\)/)

    const closeMatch = script.match(/function closeExpertTaskRoom\(\) \{[\s\S]*?\n  \}/)
    assert.ok(closeMatch, 'closeExpertTaskRoom present')
    const closeBody = closeMatch[0]
    const viewChangeAt = closeBody.indexOf("onViewChange(false, {}, { layout: 'overview'")
    const restoreAt = closeBody.indexOf('restoreTaskRoomReturnState(returnState)')
    assert.ok(viewChangeAt >= 0 && restoreAt >= 0, 'overview layout and restore in closeExpertTaskRoom')
    assert.ok(viewChangeAt < restoreAt, 'must clear task-room layout before restore/renderShelf')
  })

  it('keeps the shared dialog for details only, not for launching', () => {
    // 启动弹窗（含 DAG 预览、Daemon 上下文表单）已被运行视图的确认输入取代
    assert.doesNotMatch(script, /wrapWorkflowLaunchBody|data-dag-toggle/)
    assert.doesNotMatch(script, /wbDaemonIntent|wbDaemonSlug|wbDaemonPrd|wbDaemonProject/)
    assert.doesNotMatch(script, /function renderWorkflowDagHtml\(|function renderWorkflowDagSummaryHtml\(/)
    assert.match(script, /function loadWorkflowDetail\(/)
    assert.match(script, /function mergeWorkflowItem\(/)
    assert.match(html, /id="wbModalConfirm" hidden/)
  })

  it('opens workflow dialogue room from card body and run icon', () => {
    assert.match(script, /function openWorkflowDialogueRoom\(/)
    assert.match(script, /function workflowPrimaryExpert\(/)
    assert.match(script, /function openWorkflowAsTask\(/)
    assert.match(script, /function beginWorkflowRun\(/)
    assert.match(script, /function openWorkflowDetail\(/)
    assert.match(script, /function beginExpertTask\(/)
    assert.match(script, /kind: 'workflow-detail'/)
    assert.match(script, /action === 'inspect' \|\| action === 'use'/)
    assert.match(script, /data-flow-action="inspect"/)
    assert.match(script, /data-icon="play"/)
    assert.match(script, /await openWorkflowDialogueRoom\(/)
    assert.match(script, /void openWorkflowDialogueRoom\(/)
    assert.match(script, /openExpertTaskRoom\(/)
    assert.match(script, /resolvedWorkflow \? '对话中' : '协作中'/)
    assert.match(script, /forceList: true/)
    assert.match(script, /wb-side-step-list/)
    assert.match(script, /现在可以在左侧对话推进本工作流/)
    assert.doesNotMatch(script, /data-workflow-room-action="run"/)
    assert.match(script, /runMode: resolvedWorkflow \? 'workflow-chat' : 'expert-chat'/)
    assert.match(script, /title="开始运行"/)
    assert.match(script, /aria-label="开始运行"/)
    assert.match(script, /aria-label="打开工作流对话：\$\{escAttr\(displayName\)\}"/)
    assert.match(layoutCss, /\.wb-side-workflow/)
    assert.match(layoutCss, /\.wb-side-workflow-io/)
    assert.match(layoutCss, /\.wb-side-block/)
    assert.match(layoutCss, /\.wb-side-step-list/)
    const shelfCardMatch = script.match(/function shelfCardHtml\(item\) \{[\s\S]*?\n  \}/)
    assert.ok(shelfCardMatch, 'shelfCardHtml present')
    assert.doesNotMatch(shelfCardMatch[0], /wb-shelf-run|workflow-start|data-flow-action="use"/)
  })

  it('keeps DAG internals out of the shelf cards', () => {
    assert.match(script, /function workflowOutcomeText\(item = \{\}\)/)
    assert.match(script, /function workflowInputText\(item = \{\}\)/)
    assert.match(script, /summary: item\.summary/)
    assert.doesNotMatch(script, /function nodeIoSummary\(/)
    const shelfCardMatch = script.match(/function shelfCardHtml\(item\) \{[\s\S]*?\n  \}/)
    assert.ok(shelfCardMatch, 'shelfCardHtml present')
    assert.doesNotMatch(shelfCardMatch[0], /wb-dag-panel|renderShelfPackageDagHtml/)
  })

  it('renders polished shelf cards with mark and compact chips', () => {
    assert.match(script, /function shelfChipText\(/)
    assert.match(script, /function shelfCardBlurb\(/)
    assert.match(script, /function shelfDomainIcon\(/)
    assert.match(script, /function workflowBriefFlowHtml\(/)
    const shelfCardMatch = script.match(/function shelfCardHtml\(item\) \{[\s\S]*?\n  \}/)
    assert.ok(shelfCardMatch, 'shelfCardHtml present')
    assert.match(shelfCardMatch[0], /wb-shelf-mark/)
    assert.match(shelfCardMatch[0], /shelfDomainIcon\(domain\)/)
    assert.match(shelfCardMatch[0], /wb-shelf-card-top/)
    assert.match(shelfCardMatch[0], /wb-shelf-card-copy/)
    assert.match(shelfCardMatch[0], /wb-shelf-title-row/)
    assert.match(shelfCardMatch[0], /wb-shelf-chips/)
    assert.match(shelfCardMatch[0], /wb-shelf-chip/)
    assert.match(shelfCardMatch[0], /wb-shelf-card-bottom/)
    assert.match(shelfCardMatch[0], /简要流程/)
    assert.match(shelfCardMatch[0], /data-domain="\$\{escAttr\(domain\)\}"/)
    assert.doesNotMatch(shelfCardMatch[0], /wb-shelf-chip-steps|<dt>需要<\/dt>/)
    assert.doesNotMatch(shelfCardMatch[0], /data-workflow-manage="fork"|data-workflow-manage="edit"|data-workflow-manage="delete"/)
    assert.match(shelfCss, /\.wb-shelf-chip\s*\{[^}]*border:\s*1px solid/s)
    assert.match(shelfCss, /\.wb-shelf-card-top\s*\{/)
    assert.match(shelfCss, /\.wb-shelf-brief-flow\s*\{/)
  })

  it('keeps brief-flow step labels fully readable without a narrow max-width clip', () => {
    const briefFlow = script.match(/function workflowBriefFlowHtml\(stepLabels = \[\]\) \{[\s\S]*?\n  \}/)?.[0] || ''
    assert.ok(briefFlow, 'workflowBriefFlowHtml present')
    assert.match(briefFlow, /title="\$\{escAttr\(label\)\}"/)
    assert.match(shelfCss, /\.wb-workflow-manage-flow-step\s*\{[^}]*max-width:\s*100%/s)
    assert.doesNotMatch(shelfCss, /\.wb-workflow-manage-flow-step\s*\{[^}]*max-width:\s*9\.5em/s)
  })

  it('shows refined footer meta with steps and primary action', () => {
    assert.match(script, /function shelfFooterMetaHtml\(/)
    assert.doesNotMatch(script, /function shelfUpdatedParts\(/)
    assert.doesNotMatch(script, /wb-shelf-updated/)
    assert.doesNotMatch(script, /模板修改于/)
    assert.doesNotMatch(script, /更新于 \$\{esc\(updated\.relative\)\}/)
    assert.match(script, /wb-shelf-actions/)
    assert.match(script, /wb-shelf-icon-btn is-primary/)
    assert.match(shelfCss, /\.wb-shelf-meta/)
    assert.doesNotMatch(shelfCss, /\.wb-shelf-updated/)
    assert.match(shelfCss, /\.wb-shelf-actions/)
    assert.match(shelfCss, /\.wb-shelf-icon-btn\.is-primary/)
    assert.match(shelfCss, /justify-content:\s*space-between/)
    const shelfCardMatch = script.match(/function shelfCardHtml\(item\) \{[\s\S]*?\n  \}/)
    assert.ok(shelfCardMatch, 'shelfCardHtml present')
    assert.match(shelfCardMatch[0], /shelfFooterMetaHtml\(item, steps\)/)
    assert.match(shelfCardMatch[0], /wb-shelf-actions/)
    assert.match(shelfCardMatch[0], /is-primary/)
    assert.doesNotMatch(shelfCardMatch[0], /data-flow-action="fork"|data-flow-action="graph"/)
  })

  it('uses a low-cognitive-load shelf instead of a dashboard wall', () => {
    assert.doesNotMatch(html, /wb-overview-stats/)
    assert.doesNotMatch(html, /Command center/i)
    assert.doesNotMatch(html, /data-goal-path=/)
    assert.doesNotMatch(html, /id="wbFlowLibraryGroups"/)
    assert.doesNotMatch(html, /id="wbConsoleAttention"/)
    assert.doesNotMatch(html, /id="wbConsoleRuns"/)
    assert.doesNotMatch(html, /id="wbConsoleReadiness"/)
    assert.match(html, /id="wbShelfGrid"/)
    assert.match(html, /id="wbDaemonModeDetail"/)
    assert.doesNotMatch(html, /wb-goal-legacy/)
    assert.doesNotMatch(html, /id="wbAgentManagerForm"/)
  })

  it('retires today todos from the workbench and the assistant menu', () => {
    assert.doesNotMatch(html, /id="wbShelfTodos"/)
    assert.doesNotMatch(html, /id="wbTodoList"/)
    assert.doesNotMatch(html, /id="km-fab-todo"/)
    assert.doesNotMatch(script, /function loadTodos\(/)
    assert.doesNotMatch(script, /function addTodo\(/)
    assert.doesNotMatch(script, /knowme:add-todo/)
    assert.doesNotMatch(shelfCss, /\.wb-shelf-todos\s*\{/)
  })

  it('uses a single mixed shelf with provenance badges', () => {
    // 顶部两 Tab 划分「工作流 / 管理」，不再按来源把货架切成两片
    assert.doesNotMatch(html, /data-wb-mode="team"/)
    assert.doesNotMatch(html, /data-wb-mode="mine"/)
    assert.doesNotMatch(html, /id="wbAgentShelf"/)
    assert.match(html, /id="wbShelfGrid"/)
    assert.match(script, /function shelfProvenanceLabel\(source\)/)
    assert.match(script, /wb-shelf-provenance-\$\{provenanceClass\}/)
    assert.match(script, /function shelfItems\(\)/)
    assert.doesNotMatch(script, /function setWorkMode\(mode\)/)
    assert.doesNotMatch(script, /activeWorkMode === 'mine'/)
  })

  it('keeps the todo store and IPC intact after the UI is retired', () => {
    // UI 入口已下线，但持久化数据与 IPC 保留以便将来复用，不删用户数据
    const store = fs.readFileSync(path.join(__dirname, '..', 'src', 'lib', 'workbench-todo-store.js'), 'utf8')
    assert.match(store, /function createStore\(file\)/)
    assert.match(store, /clearDone/)
    assert.match(store, /importLegacy/)
    assert.match(main, /workbench-todos\.json/)
    assert.match(workbenchLocalStoresIpc, /ipcMain\.handle\('workbench-todo-list'/)
    assert.match(workbenchLocalStoresIpc, /ipcMain\.handle\('workbench-todo-add'/)
    assert.match(workbenchLocalStoresIpc, /ipcMain\.handle\('workbench-todo-clear-done'/)
    assert.match(preload, /workbenchTodoList:/)
    assert.match(preload, /workbenchTodoImportLegacy:/)
    // 渲染层的待办入口彻底移除
    assert.doesNotMatch(script, /TODO_STORAGE_KEY/)
    assert.doesNotMatch(script, /function clearDoneTodos\(/)
    assert.doesNotMatch(html, /id="wbTodoClear"/)
  })

  it('persists composable work modes behind bounded main-process IPC', () => {
    const store = fs.readFileSync(path.join(__dirname, '..', 'src', 'lib', 'workbench-mode-store.js'), 'utf8')
    assert.match(store, /const BUILTIN_MODE_IDS = Object\.freeze\(\['office', 'engineering', 'visual'\]\)/)
    assert.match(store, /const MAX_BINDINGS_PER_MODE = 32/)
    assert.match(main, /workbench-modes\.json/)
    assert.match(workbenchModeIpc, /ipcMain\.handle\('workbench-mode-list'/)
    assert.match(workbenchModeIpc, /ipcMain\.handle\('workbench-mode-select'/)
    assert.match(workbenchModeIpc, /ipcMain\.handle\('workbench-mode-bind-expert'/)
    assert.match(workbenchModeIpc, /ipcMain\.handle\('workbench-mode-unbind-expert'/)
    assert.match(main, /isExpertAvailableForWorkbench\(expertId\)/)
    assert.match(preload, /workbenchModeList:/)
    assert.match(preload, /workbenchModeSelect:/)
    assert.match(preload, /workbenchModeBindExpert:/)
    assert.match(preload, /workbenchModeUnbindExpert:/)
    assert.match(script, /async function selectMode\(modeId\)/)
    assert.match(script, /async function refreshModes\(\)/)
  })

  it('renders recent tasks as summary cards instead of exposing internal slugs', () => {
    assert.match(script, /function taskRecentSummary\(task\)/)
    assert.match(script, /function renderTaskRecentRow\(task\)/)
    assert.match(script, /wb-task-card/)
    assert.match(script, /class="wb-task-summary"/)
    assert.match(script, /wb-task-schedule-mark/)
    assert.match(script, /agentAvatarMark\(expert, 'wb-task-card-avatar'/)
    assert.match(script, /resolveTaskManageExpert\(task\)/)
    assert.match(layoutCss, /\.wb-task-card-avatar/)
    assert.doesNotMatch(script, /data-task-schedule="/)
    assert.match(script, /id="wbTaskComposerScheduleEnabled"/)
    assert.match(html, /id="wbTaskManage"[\s\S]*?data-icon="settingsLine"/)
    assert.match(html, /id="wbShelfTaskManage"[\s\S]*?data-icon="settingsLine"/)
    assert.match(html, /id="wbShelfTaskManage"[^>]*aria-label="管理工作流运行"/)
    assert.doesNotMatch(html, /定时任务/)
    assert.match(script, /function openTaskManageHub/)
    assert.match(script, /function taskManageScopeList/)
    assert.match(script, /openTaskManageHub\('workflow'\)/)
    assert.match(script, /function renderTaskManageItem/)
    assert.match(script, /function applyTaskManageSelectStrategy/)
    assert.match(script, /data-task-manage="select-older-3m"/)
    assert.match(script, /wb-task-manage-avatar/)
    assert.match(script, /wb-task-manage-progress/)
    assert.match(script, /管理工作流运行/)
    assert.match(script, /workbenchTaskArchive/)
    assert.match(script, /<span class="wb-task-state">\$\{esc\(meta\.label\)\}<\/span>/)
    assert.doesNotMatch(script, /data-task-open="\$\{escAttr\(task\.slug\)\}"/)
    assert.doesNotMatch(script, /wb-task-summary">\$\{esc\(task\.slug\)\}/)
  })

  it('collapses quick experts to one preview row with more toggle', () => {
    assert.match(html, /id="wbTaskQuickToggle"/)
    assert.match(script, /const TASK_QUICK_PREVIEW = 3/)
    assert.match(script, /function paintTaskQuickGrid\(\)/)
    assert.match(script, /function syncTaskQuickToggle\(total\)/)
    assert.match(layoutCss, /\.wb-task-quick-grid\s*\{[^}]*grid-template-columns:\s*repeat\(3/s)
    assert.doesNotMatch(script, /experts\.slice\(0,\s*8\)/)
  })

  it('renders shelf cards from workflow packages returned by workbench-load', () => {
    assert.match(script, /workflows:\s*Array\.isArray\(res\.workflows\)/)
    assert.match(script, /function renderShelf\(\)/)
    assert.match(script, /class="wb-shelf-card/)
    assert.doesNotMatch(script, /class="wb-workflow-card"/)
  })

  it('tells the truth when the shelf has nothing to run', () => {
    assert.match(script, /还没有工作流/)
    assert.match(script, /function shelfSupplyHint\(\)/)
    assert.match(script, /data-shelf-action="studio">新建工作流/)
    assert.match(script, /点「全部」或清空搜索再看看/)
    assert.doesNotMatch(script, /清除筛选/)
    assert.doesNotMatch(html, /id="wbShelfFilterClear"|清除筛选/)
    assert.match(shelfCss, /\.wb-shelf-empty\s*\{/)
  })

  it('keeps professional domains fully visible and defaults to no filtering', () => {
    assert.match(html, /id="wbDomainSwitcher" role="group" aria-label="领域筛选"/)
    assert.match(html, /data-domain="all" aria-pressed="true"/)
    assert.match(html, /data-domain="office"/)
    assert.match(html, /data-domain="engineering"/)
    assert.match(html, /data-domain="visual"/)
    assert.match(script, /let consoleDomain = 'all'/)
    assert.match(consoleCss, /\.wb-domain-chip:focus-visible/)
    // 领域 chip 只筛货架：不得 selectMode IPC、不得重绘 Studio、同域点击短路
    const domainFn = script.match(/function selectConsoleDomain\(domainId\) \{[\s\S]*?\n  \}/)
    assert.ok(domainFn, 'selectConsoleDomain present')
    assert.doesNotMatch(domainFn[0], /selectMode\(/)
    assert.doesNotMatch(domainFn[0], /renderStudio\(/)
    assert.match(domainFn[0], /if \(id === consoleDomain\)/)
    assert.doesNotMatch(script, /setWorkbenchPage\(activePage/)
  })

  it('makes the shelf card the single launch entry', () => {
    assert.doesNotMatch(html, /id="wbLaunchDrawer"/)
    assert.doesNotMatch(html, /id="wbConsoleNewRun"/)
    assert.doesNotMatch(html, /class="wb-console-launch"/)
    assert.doesNotMatch(html, /data-goal-template=/)
    assert.match(script, /function openLaunchDrawer\(patch = \{\}\) \{[\s\S]*?setSurface\('run', \{ force: true \}\)/)
    assert.match(script, /data-flow-action="inspect"/)
    assert.match(script, /模式仍用于推荐排序，不再把普通用户挡在空目录之外/)
  })

  it('keeps local and pipeline-service expert catalogs separate across refresh', () => {
    assert.match(workbenchLoadIpc, /partitionAgentExperts\(localAgents, daemon\)/)
    assert.match(workbenchLoadIpc, /agents:\s*catalogs\.localAgents/)
    assert.match(workbenchLoadIpc, /daemonAgents:\s*catalogs\.daemonAgents/)
    assert.match(workbenchLoadIpc, /repositoryAgents/)
    assert.match(script, /agentSource:\s*String\(res\.agentSource \|\| 'none'\)/)
    assert.match(script, /daemonAgents:\s*Array\.isArray\(res\.daemonAgents\)/)
    assert.match(capabilityHubService, /payload\.origin === 'daemon' \|\| payload\.source === 'daemon'/)
    assert.match(capabilityHubService, /readonly_daemon_agent/)
    assert.match(script, /btnReload && btnReload\.addEventListener\('click', async \(\) => \{[\s\S]*loaded = false[\s\S]*await load\(\)/)
  })

  it('binds templates to daemon execution with repository fallback', () => {
    assert.match(gameIpc, /workbenchRepo\.resolveActiveRepo\(loadSourcesStore\(\)\)/)
    assert.match(gameIpc, /ipcMain\.handle\('game-workbench-handoff'/)
    assert.match(workbenchLoadIpc, /workbenchRepo\.resolveActiveRepo\(loadSourcesStore\(\)\)/)
    assert.match(workbenchLoadIpc, /workbenchRepo\.resolveWorkflowFile\(repo\.root,\s*rel\)/)
    assert.match(workbenchDaemonIpc + main, /workbenchDaemon\.createClient\(\{\s*endpoint,\s*token\s*\}\)/)
    assert.match(workbenchDaemonIpc + main + workbenchAuthIpc, /workbenchAuth\.resolveToken\(settings\)/)
    assert.match(workspace, /workbenchOn && window\.Workbench\) window\.Workbench\.load\(\)/)
    assert.match(html, /id="wbRunner"/)
    assert.match(script, /window\.api\.workbenchDaemonStart/)
    assert.match(script, /window\.api\.workbenchDaemonTask/)
    assert.match(script, /已进入任务工作间/)
    assert.match(script, /window\.api\.workbenchWorkflow\(merged\)/)
    assert.match(script, /handleDaemonAuthFailure/)
    assert.match(script, /openWorkbenchAuthHelp/)
    assert.match(script, /function confirmModal\(\)/)
    assert.doesNotMatch(script, /actionButton\('daemon-clarify'/)
    assert.match(script, /knowme-daemon-hitl-submitted/)
    assert.match(html, /agent-daemon-hitl/)
  })

  it('starts a workflow straight from the run surface without a second confirm dialog', () => {
    assert.match(script, /function startWorkflowRun\(/)
    assert.match(script, /async function beginDaemonRun\(/)
    assert.match(script, /function beginLocalRun\(/)
    // 旧的启动弹窗（openWorkflow → wbWorkflowModal）会遮住整个界面并要求二次确认
    assert.doesNotMatch(script, /function openWorkflow\(/)
    assert.doesNotMatch(script, /renderDaemonLaunchBody|renderLocalLaunchBody/)
    assert.doesNotMatch(script, /data-fork-workflow/)
    assert.doesNotMatch(html, /开始任务/)
  })

  it('exposes semantic daemon IPC without an arbitrary request bridge', () => {
    assert.match(preload, /workbenchDaemonStart/)
    assert.match(preload, /workbenchDaemonTask/)
    assert.match(preload, /workbenchDaemonGate/)
    assert.match(preload, /workbenchDaemonClarify/)
    assert.match(preload, /workbenchAuthStatus/)
    assert.match(preload, /workbenchAuthLogin/)
    assert.match(preload, /workbenchAuthLogout/)
    assert.match(preload, /workbenchDaemonOverview/)
    assert.match(preload, /onWorkbenchAuthChanged/)
    assert.match(preload, /workbench-auth-changed/)
    assert.doesNotMatch(preload, /workbenchDaemonRequest/)
    assert.match(workbenchAuthIpc, /ipcMain\.handle\('workbench-auth-status'/)
    assert.match(workbenchAuthIpc, /ipcMain\.handle\('workbench-auth-login'/)
    assert.match(workbenchAuthIpc, /ipcMain\.handle\('workbench-auth-logout'/)
    assert.match(workbenchDaemonIpc, /ipcMain\.handle\('workbench-daemon-overview'/)
    assert.match(workbenchBootstrapIpc, /ipcMain\.handle\('workbench-bootstrap-status'/)
    assert.match(workbenchLoadIpc, /ipcMain\.handle\('workbench-load'/)
    assert.match(main, /notifyWorkbenchAuthChanged/)
    assert.match(main, /workbench-auth-changed/)
    assert.match(script, /onWorkbenchAuthChanged/)
    assert.match(script, /handleWorkbenchAuthChanged/)
    assert.match(script, /workbenchDaemonOverview/)
  })

  it('adds an automation tab with dedicated IPC surface', () => {
    assert.doesNotMatch(html, /id="wbTabAutomation"/)
    assert.match(html, /id="wbAutomationPage"/)
    assert.match(html, /id="wbAutomationList"/)
    assert.match(html, /id="wbAutomationTemplates"/)
    assert.match(html, /id="wbAutomationModal"/)
    assert.match(html, /id="wbAutomationModalBody"/)
    assert.match(html, /id="wbAutomationModalSave"/)
    assert.match(script, /function renderAutomation\(\)/)
    assert.match(script, /function openAutomationModal\(/)
    assert.match(script, /function saveAutomationModal\(/)
    assert.match(script, /workbenchAutomationCreate/)
    assert.match(script, /workbenchAutomationUpdate/)
    assert.match(script, /workbenchAutomationDelete/)
    assert.match(script, /workbenchAutomationList/)
    assert.match(workbenchAutomationIpc, /ipcMain\.handle\('workbench-automation-list'/)
    assert.match(workbenchAutomationIpc, /ipcMain\.handle\('workbench-automation-run-now'/)
    assert.match(workbenchAutomationIpc, /ipcMain\.handle\('workbench-automation-delete'/)
    assert.match(preload, /workbenchAutomationList/)
    assert.match(preload, /workbenchAutomationRunNow/)
    assert.match(preload, /workbenchAutomationFeishuTargets/)
    assert.match(preload, /workbenchAutomationCreate/)
    assert.match(preload, /workbenchAutomationUpdate/)
    assert.match(preload, /workbenchAutomationDelete/)
  })

  it('shows automation as an independent surface mode', () => {
    assert.match(html, /\.app\.mode-agent\.mode-automation:not\(\.agent-has-document\) #workSurfaceWrap \{ display:flex; \}/)
    assert.match(layoutCss, /\.app\.mode-automation #workSurfaceWrap \.workbench \{ display:flex;/)
    assert.match(layoutCss, /\.app\.mode-automation #wbShelfSurface,\s*\n\.app\.mode-automation #wbRunSurface \{ display:none !important; \}/)
    assert.match(layoutCss, /\.app\.mode-automation #wbAutomationPage \{ display:block !important; \}/)
    assert.match(workspace, /shell\.classList\.toggle\('mode-automation', inAutomation\)/)
    assert.match(workspace, /function openWorkbenchHome\(\)/)
  })

  it('uses the whole automation template card as an accessible create action', () => {
    assert.match(script, /function automationTemplateIcon\(templateId\)/)
    assert.match(script, /<button type="button" class="wb-automation-template" data-auto-template-action="create"/)
    assert.match(script, /wb-automation-template-icon/)
    assert.match(script, /data-icon="\$\{automationTemplateIcon\(template\.id\)\}"/)
    assert.match(script, /\|\| 'automation'/)
    assert.doesNotMatch(script, />使用模板<\/button>/)
    assert.match(workbenchCss, /\.wb-automation-template:focus-visible\s*\{/)
    assert.match(workbenchCss, /\.wb-automation-template:hover\s*\{/)
  })

  it('exposes single-shelf provenance labels and manage-page fork actions', () => {
    assert.match(script, /function shelfProvenanceLabel\(source\)/)
    assert.match(script, /wb-shelf-provenance-\$\{provenanceClass\}/)
    assert.match(script, /function shelfCardHtml\(item\)/)
    assert.match(script, /function workflowManageItemHtml\(/)
    assert.match(script, /data-workflow-manage="fork"/)
    assert.doesNotMatch(script, /function shelfCardHtml\(item\) \{[\s\S]*?data-flow-action="fork"[\s\S]*?\n  \}/)
    assert.match(script, /function forkWorkflowPackage\(item\)/)
    assert.match(script, /function workflowSourceLabel\(source\)/)
    assert.match(script, /function executionBackendLabel\(item\)/)
    assert.doesNotMatch(html, /data-source="official"/)
    assert.doesNotMatch(script, /function workModeOf\(item = \{\}\)/)
  })

  it('routes every launch through the launch controller from the run surface', () => {
    assert.match(script, /async function launchPreparedIntent\(/)
    assert.match(script, /await launchPreparedIntent\(\)/)
    assert.match(script, /setRunStage\('running'\)/)
    assert.doesNotMatch(script, /if \(await openAgentGraph\(value\)\) return/)
    assert.doesNotMatch(html, /data-goal-path-continue=/)
  })

  it('wires launch controller through main, preload, and renderer', () => {
    assert.match(workbenchLaunchIpc, /workbench-launch-assess/)
    assert.match(workbenchLaunchIpc, /workbench-launch-save/)
    assert.match(workbenchLaunchIpc, /workbench-launch-start/)
    assert.match(workbenchLaunchIpc, /workbench-launch-complete/)
    assert.match(main, /registerCoreIpc|workbenchLaunchController/)
    assert.match(preload, /workbenchLaunchAssess:/)
    assert.match(preload, /workbenchLaunchSave:/)
    assert.match(preload, /workbenchLaunchStart:/)
    assert.match(script, /async function updateLaunchIntent\(/)
    assert.match(script, /async function ingestLaunchRequest\(/)
    assert.match(script, /function resolveWorkflowExecutionSource\(item\)/)
    assert.match(script, /legacy-local/)
    assert.match(script, /ingestLaunchRequest\(res\.launchRequest/)
  })

  it('restores running tasks from draft during workbench load', () => {
    assert.match(script, /async function restoreTaskFromDraft\(\)/)
    assert.match(script, /async function clearStaleDaemonTaskDraft\(\)/)
    assert.match(script, /function daemonDraftPhaseIsTerminal\(/)
    assert.match(script, /resolveReturnSurface\(intent\?\.returnState\?\.surface \|\| 'daemon'\)/)
    assert.match(script, /returnSurface: intent\.returnState\?\.surface \|\| 'daemon'/)
    assert.match(script, /void refreshRunDirectory\(\)/)
    assert.match(script, /\|\| 'daemon'\s*\n\s*\)/)
    assert.match(script, /if \(draft\.executionSource === 'agent-graph' && draft\.rootRunId\)/)
    assert.match(script, /await restoreTaskFromDraft\(\)/)
    assert.match(script, /async function dismissRunInputDraft\(\)/)
    assert.match(script, /void dismissRunInputDraft\(\)/)
    assert.match(script, /status: 'cancelled', step: 'intent'/)
    const restoreDraft = script.match(/async function restoreTaskFromDraft\(\) \{[\s\S]*?\n  \}/)?.[0] || ''
    assert.match(restoreDraft, /preparing 且无真实 run：只是确认输入草稿，预填目标，不自动弹窗/)
    assert.match(restoreDraft, /daemonDraftPhaseIsTerminal/)
    assert.match(restoreDraft, /clearStaleDaemonTaskDraft/)
    assert.doesNotMatch(restoreDraft, /openLaunchDrawer\(/)
    assert.doesNotMatch(restoreDraft, /await openDaemonTask\(draft\.slug, \{ silent: true \}\)/)
    const restoreLaunch = script.match(/async function restoreLaunchIntentFromStores\(\) \{[\s\S]*?\n  \}/)?.[0] || ''
    assert.doesNotMatch(restoreLaunch, /openLaunchDrawer\(/)
    assert.match(restoreLaunch, /不强制打开「填写本次信息」|预填目标即可/)
    const backToRun = script.match(/async function backToRunList\(\) \{[\s\S]*?\n  \}/)?.[0] || ''
    assert.match(backToRun, /void refreshRunDirectory\(\)/)
    assert.doesNotMatch(backToRun, /await refreshRunDirectory\(\)/)
  })

  it('shows an editable workflow name in the studio head title', () => {
    assert.match(html, /id="wbStudioTitle"/)
    assert.match(html, /id="wbStudioTitleInput"/)
    assert.doesNotMatch(html, /wb-studio-head-title">\s*<strong>编排工作流<\/strong>/)
    assert.match(script, /function studioWorkflowDisplayName\(/)
    assert.match(script, /function studioHeadMetaText\(/)
    assert.match(script, /function beginStudioTitleEdit\(/)
    assert.match(script, /function commitStudioTitleEdit\(/)
    assert.match(script, /编排工作流 · \$\{nodes\.length\} 节点/)
    assert.match(shelfCss, /\.wb-studio-title-btn/)
    assert.match(shelfCss, /\.wb-studio-title-input/)
  })

  it('keeps workbench styling external and exposes distinct operational states', () => {
    const inlineStyles = [...html.matchAll(/<style>([\s\S]*?)<\/style>/g)].map(match => match[1]).join('\n')
    assert.doesNotMatch(inlineStyles, /(?:^|[\s,])\.wb-|\.mode-workbench/)
    assert.match(html, /id="wbRunStatus" role="status" aria-live="polite" aria-atomic="true"/)
    assert.match(consoleCss, /\.wb-run-status\.tone-cancelled/)
    assert.match(consoleCss, /\.wb-task-chip\.cancelled/)
    assert.match(consoleCss, /\.wb-task-chip\.cancelled \.wb-task-state-dot/)
    assert.match(consoleCss, /\.wb-flow-library-action:focus-visible/)
    assert.match(consoleCss, /@media \(prefers-reduced-motion:reduce\)/)
    assert.match(consoleCss, /@media \(max-width:760px\)/)
  })
})
