/**
 * 工作台 workflow 模板区静态接线回归
 */
const { describe, it } = require('node:test')
const assert = require('node:assert')
const fs = require('node:fs')
const path = require('node:path')

const html = fs.readFileSync(path.join(__dirname, '..', 'src', 'workspace.html'), 'utf8')
const script = fs.readFileSync(path.join(__dirname, '..', 'src', 'workbench.js'), 'utf8')
const workspace = fs.readFileSync(path.join(__dirname, '..', 'src', 'workspace.js'), 'utf8')
const main = fs.readFileSync(path.join(__dirname, '..', 'src', 'main.js'), 'utf8')
const preload = fs.readFileSync(path.join(__dirname, '..', 'src', 'preload.js'), 'utf8')

describe('workbench workflow templates', () => {
  it('provides the template region and responsive card styles', () => {
    assert.match(html, /选择工作流/)
    assert.match(html, /id="wbOverviewTitle"/)
    assert.match(html, /懂你的智能体团队/)
    assert.match(html, /id="wbStatWorkflows"/)
    assert.match(html, /id="wbStatAgents"/)
    assert.match(html, /id="wbDaemonStatus"/)
    assert.doesNotMatch(html, /id="wbHomeStart"/)
    assert.doesNotMatch(html, /\.wb-home-action\s*\{/)
    assert.match(html, /id="wbTaskList"/)
    assert.match(html, /id="wbWorkflowList"/)
    assert.match(html, /\.wb-workflow-list\s*\{[^}]*auto-fill/s)
    assert.match(html, /\.wb-workflow-desc\s*\{[^}]*text-overflow:ellipsis/s)
  })

  it('keeps the home hero focused and the offline status product-facing', () => {
    assert.doesNotMatch(script, /btnHomeStart/)
    assert.match(script, /: '离线模式 · 仅可浏览'/)
    assert.match(script, /elDaemonStatus\.title = authPending/)
    assert.match(script, /daemon\.online \? '工作服务已连接，可以启动工作流' : '点击查看如何连接工作服务'/)
    assert.match(html, /离线模式 · 仅可浏览/)
    assert.match(html, /min-height:204px/)
  })

  it('turns the offline status into an actionable path instead of a dead end', () => {
    assert.match(html, /<button type="button" class="wb-daemon-status offline" id="wbDaemonStatus">/)
    assert.match(html, /\.wb-daemon-status\s*\{[^}]*cursor:pointer/s)
    assert.match(html, /\.wb-daemon-status:focus-visible\s*\{/)
    assert.match(script, /function openDaemonHelp\(\)/)
    assert.match(script, /if \(auth\.authEnabled && auth\.state === 'required'\) openWorkbenchAuthHelp\(\)/)
    assert.match(script, /else openDaemonHelp\(\)/)
    assert.match(script, /kind: 'notice'/)
    assert.match(script, /modal\.kind === 'notice'/)
    // 首页不再重复提供工作流入口，统一由顶部 Tab 进入
    assert.doesNotMatch(html, /开始工作流/)
    assert.doesNotMatch(html, /浏览工作流/)
  })

  it('distinguishes workbench task command from regular Agent chat', () => {
    assert.match(html, /workbench-chat-brand/)
    assert.match(html, /任务协作/)
    assert.match(html, /首页/)
    assert.match(html, /工作流/)
    assert.match(html, /id="wbRunStatus"/)
    assert.match(html, /workbench-task-brief\.js/)
    assert.match(script, /wb-task-state-dot/)
    assert.match(script, /factualBrief/)
    assert.match(script, /localWaiting/)
    assert.match(workspace, /WorkspaceAgent\.setSurfaceMode\(workbenchOn \? 'workbench' : 'agent'\)/)
    const agentScript = fs.readFileSync(path.join(__dirname, '..', 'src', 'workspace-agent.js'), 'utf8')
    assert.match(agentScript, /function setSurfaceMode\(mode\)/)
    assert.match(agentScript, /SURFACE_SESSION_KEY/)
    assert.match(agentScript, /WORKBENCH_SESSION_GOAL/)
    assert.match(agentScript, /activateSurfaceSession\(surfaceMode\)/)
    assert.match(agentScript, /function enterWorkbenchTask\(context/)
    assert.match(agentScript, /工作台任务上下文/)
    assert.match(agentScript, /任务事实门禁/)
    assert.match(agentScript, /补充任务要求或材料；进度与审批请看右侧流程/)
  })

  it('uses a full-width home and opens a task-scoped conversation workspace', () => {
    assert.match(html, /\.app\.mode-workbench \.agent-col\s*\{\s*display:none/)
    assert.match(html, /\.agent-col\s*\{[^}]*flex:1 1 0/s)
    assert.match(html, /\.pane-wrap\s*\{[^}]*flex:1 1 0/s)
    assert.match(html, /\.app\.mode-workbench\.workbench-task-active \.agent-col\s*\{[^}]*display:flex[^}]*flex:1 1 0/s)
    assert.match(html, /\.app\.mode-workbench\.workbench-task-active #workSurfaceWrap\s*\{[^}]*flex:1 1 0/s)
    assert.doesNotMatch(html, /:has\(#wbRunner:not\(\[hidden\]\)\) \.agent-col/, 'runner state must not reopen chat on the home page')
    assert.match(workspace, /function setWorkbenchTaskView\(active, context/)
    assert.match(workspace, /workbench-task-active/)
    assert.match(workspace, /onViewChange: setWorkbenchTaskView/)
    assert.match(workspace, /function openAgentChat\(\)/)
    assert.match(workspace, /workbenchOn = false/)
    assert.match(script, /onViewChange\(active, active \? workbenchTaskContext\(\) : \{\}\)/)
    assert.match(script, /setWorkbenchPage\('tasks', \{ force: true \}\)/)
    assert.match(script, /run\.intent = intent/)
    assert.match(script, /run\.intent = \(item && item\.intent\)/)
  })

  it('shows a business workflow graph in the task context rail', () => {
    assert.match(html, /id="wbRunStatus"/)
    assert.match(html, /id="wbRunProgress"/)
    assert.match(html, /你现在要做什么/)
    assert.match(html, /id="wbRunNextAction"/)
    assert.match(html, /id="wbRunGoal"/)
    assert.match(html, /id="wbRunAgents"/)
    assert.match(html, /id="wbRunGraph"/)
    assert.match(html, /id="wbRunArtifacts"/)
    assert.match(html, /\.wb-graph-node\.active/)
    assert.match(html, /\.wb-run-agent\.is-active/)
    assert.match(script, /function graphNodes\(\)/)
    assert.match(script, /function renderTaskContext\(\)/)
    assert.match(script, /function applyTaskProjection\(/)
    assert.match(script, /run\.projection\.graphNodes/)
    assert.doesNotMatch(script, /目标与材料/)
    assert.doesNotMatch(script, /AgentTeams 协作/)
    assert.doesNotMatch(script, /结果与交付/)
  })

  it('hydrates daemon tasks via workbench-task-projection IPC', () => {
    const projection = fs.readFileSync(path.join(__dirname, '..', 'src', 'lib', 'workbench-task-projection.js'), 'utf8')
    assert.match(projection, /function projectTaskRoom\(/)
    assert.match(main, /workbenchTaskProjection\.projectTaskRoom/)
    assert.match(main, /projection: projectDaemonTask\(raw, repo\)/)
    assert.match(main, /workbench-daemon-artifact-open/)
    assert.match(preload, /workbenchDaemonArtifactOpen/)
    assert.match(script, /workbenchDaemonArtifactOpen/)
    assert.match(script, /currentOwner/)
    assert.match(script, /degradedReason/)
    assert.match(script, /无法确认进度/)
    assert.match(script, /degradedPlaceholder/)
    assert.match(script, /open-sources/)
    assert.match(script, /该产物尚未生成或未同步/)
    assert.match(main, /resolveArtifactOpenPath/)
  })

  it('places expert resources on home and workflow controls on workflow page', () => {
    assert.ok(html.indexOf('id="wbOverviewTitle"') < html.indexOf('id="wbTeamZone"'))
    assert.ok(html.indexOf('id="wbTabTasks"') < html.indexOf('id="wbStartTitle"'))
    assert.match(html, /\.wb-start-panel\s*\{[^}]*grid-column:span 8/s)
    assert.match(html, /\.wb-expert-panel\s*\{[^}]*grid-column:1 \/ -1/s)
    assert.match(html, /\.wb-team-list\s*\{[^}]*repeat\(auto-fill, minmax\(224px, 1fr\)\)/s)
    assert.match(html, /@media \(max-width: 980px\)[\s\S]*\.wb-start-panel, \.wb-expert-panel \{ grid-column:1 \/ -1; \}/)
    assert.match(html, /id="wbTeamToggle"[^>]*aria-expanded="false"/)
    assert.match(script, /function syncTeamDisclosure\(\)/)
    assert.match(script, /teamExpanded \? '收起专家' : `查看全部 \$\{count\} 位专家`/)
  })

  it('presents the workbench entrance as one refined welcome card', () => {
    assert.match(html, /今日工作台/)
    assert.match(html, /专注推进真正重要的工作/)
    assert.match(html, /\.wb-overview\s*\{[^}]*position:relative[^}]*border-radius:20px/s)
    assert.match(html, /\.wb-overview::before\s*\{[^}]*content:"知"/s)
    assert.doesNotMatch(html, /\.wb-overview::after\s*\{/)
    assert.doesNotMatch(html, /\.wb-agent-card:nth-child/)
    // 顶栏副标题不再复述 hero 计数，也不暴露内容来源仓库名
    assert.match(script, /elHeadSub\.textContent = data\.agents\.length/)
    assert.doesNotMatch(script, /本机服务在线/)
  })

  it('shows expert profiles with user-facing capability tags and opens their detail view', () => {
    assert.match(script, /function chineseRoleName\(agent\)/)
    assert.match(script, /function englishAgentName\(agent\)/)
    assert.match(script, /function roleIconName\(agent\)/)
    assert.match(script, /data-icon="\$\{roleIcon\}"/)
    assert.match(script, /wb-agent-name">\$\{esc\(chineseRole\)\}/)
    assert.match(script, /wb-agent-role">\$\{esc\(englishName\)\}/)
    assert.match(script, /wb-agent-desc">\$\{esc\(description\)\}/)
    // 卡片说「擅长什么」，不再暴露技能计数这类实现细节
    assert.match(script, /const capabilities = agentCapabilities\(a\)/)
    assert.match(script, /wb-agent-skill">\$\{esc\(tag\)\}/)
    assert.doesNotMatch(script, /wb-agent-status">可调度/)
    assert.doesNotMatch(script, /必备技能/)
    assert.doesNotMatch(script, /扩展技能/)
    assert.doesNotMatch(script, /wb-agent-open/)
    assert.match(script, /StickyIcons\.mount\(elTeamList\)/)
    assert.match(html, /\.wb-agent-avatar\s*\{[^}]*border-radius:16px/s)
    assert.match(html, /\.wb-agent-card\s*\{[^}]*cursor:pointer/s)
    assert.match(html, /\.wb-agent-skill\s*\{[^}]*border-radius:999px/s)
    assert.match(script, /data-agent="\$\{esc\(a\.id\)\}"/)
    assert.match(script, /aria-label="查看\$\{esc\(chineseRole\)\}详情"/)
    assert.match(script, /function openAgentDetail\(id\)/)
    assert.match(script, /card\.getAttribute\('data-agent'\)/)
  })

  it('folds expert cards by whole rows so nothing is half-cropped', () => {
    assert.match(html, /\.wb-agent-card\.is-folded\s*\{\s*display:none;\s*\}/)
    assert.doesNotMatch(html, /\.wb-team-list\.limited/)
    assert.match(script, /card\.classList\.toggle\('is-folded', !teamExpanded && hasMore && index >= visibleLimit\)/)
    assert.match(script, /btnTeamToggle\.hidden = !hasMore/)
  })

  it('keeps expert descriptions free of internal developer jargon', () => {
    const presenter = fs.readFileSync(path.join(__dirname, '..', 'src', 'lib', 'workbench-presenter.js'), 'utf8')
    assert.match(presenter, /INTERNAL_PATTERNS/)
    assert.match(presenter, /function userFacingSummary\(/)
    assert.match(presenter, /function capabilityTags\(/)
    assert.match(html, /lib\/workbench-presenter\.js/)
    assert.match(script, /function agentSummary\(/)
    assert.match(script, /function agentCapabilities\(/)
    const model = fs.readFileSync(path.join(__dirname, '..', 'src', 'lib', 'workbench-model.js'), 'utf8')
    assert.match(model, /function normalizeDisplay\(/)
  })

  it('renders expert details through the existing secondary modal', () => {
    assert.match(script, /modal\.kind === 'agent'/)
    assert.match(script, /wb-agent-detail-hero/)
    assert.match(script, /agentSummary\(agent, role\)/)
    assert.match(script, /由工作流按需调度/)
    assert.match(script, /btnModalConfirm\) btnModalConfirm\.hidden = true/)
    assert.match(script, /elTeamList && elTeamList\.addEventListener\('click'/)
  })

  it('collapses workflows and clean two-column recent cards independently', () => {
    assert.match(html, /id="wbWorkflowSections"/)
    assert.match(html, /id="wbWorkflowDailyList"/)
    assert.match(html, /id="wbWorkflowFrequentList"/)
    assert.match(html, /id="wbWorkflowOtherList"/)
    assert.match(html, /全部工作流/)
    assert.match(html, /\.wb-task-list\s*\{[^}]*grid-template-columns:repeat\(2, minmax\(0, 1fr\)\)/s)
    assert.match(html, /\.wb-task-list\.limited\s*\{[^}]*max-height:133px[^}]*overflow:hidden/s)
    assert.match(html, /\.wb-task-intent\s*\{[^}]*grid-column:2 \/ 4[^}]*grid-row:2/s)
    assert.match(html, /id="wbWorkflowToggle"[^>]*aria-expanded="false"/)
    assert.match(html, /id="wbTaskToggle"[^>]*aria-expanded="false"/)
    assert.match(script, /function syncWorkflowDisclosure\(\)/)
    assert.match(script, /function syncTaskDisclosure\(\)/)
    assert.match(script, /function categorizeWorkflows\(/)
    assert.match(script, /categories\.other/)
    assert.match(script, /elWorkflowOtherSection/)
    assert.match(script, /const hasMore = count > categories\.recommended\.length/)
    assert.match(script, /recommended = recommended\.concat\(take\(\(\) => true, 3 - recommended\.length\)\)/)
    assert.match(script, /elWorkflowDailySection\.hidden = true/)
    assert.match(script, /elWorkflowFrequentSection\.hidden = true/)
    assert.match(script, /elWorkflowOtherSection\.hidden = true/)
    assert.match(script, /renderWorkflows\(\)/)
    assert.match(script, /workflowExpanded \? '收起流程' : '查看全部流程'/)
    assert.match(script, /taskExpanded \? '收起运行' : '展开更多'/)
    assert.match(script, /elTaskList\.innerHTML = daemon\.tasks\.length/)
  })

  it('shows workflow launch modal with categorized picker and DAG rail', () => {
    assert.match(html, /\.wb-modal-split/)
    assert.match(html, /\.wb-modal-dag/)
    assert.match(html, /\.wb-dag-panel/)
    assert.match(html, /\.wb-dag-link/)
    assert.match(html, /\.wb-launch-group/)
    assert.match(html, /\.wb-modal-mask\.is-workflow-launch \.wb-modal-body[\s\S]*overflow:hidden/)
    assert.match(html, /\.wb-dag-flow[\s\S]*overflow-y:auto/)
    assert.match(html, /\.wb-dag-flow-shell/)
    assert.match(html, /\.wb-dag-head-subtitle/)
    assert.match(html, /\.wb-modal-mask\.is-workflow-launch \.wb-modal-foot[\s\S]*box-shadow/)
    assert.match(html, /\.wb-modal-mask\.is-workflow-launch/)
    assert.match(script, /function renderWorkflowDagHtml\(/)
    assert.match(script, /function renderDagConnector\(/)
    assert.match(script, /function loadWorkflowDetail\(/)
    assert.match(script, /function mergeWorkflowItem\(/)
    assert.match(script, /wrapWorkflowLaunchBody/)
    assert.match(script, /wb-launch-intro/)
    assert.doesNotMatch(script, /wb-dag-next-item/)
    assert.doesNotMatch(script, /wb-dag-io/)
    assert.match(script, /只读预览/)
    assert.match(script, /wbHelpDag/)
    assert.match(script, /wb-dag-flow-shell/)
    assert.match(script, /elModal\.classList\.toggle\('is-workflow-launch'/)
  })

  it('keeps daemon launch focused and separates required context from extras', () => {
    assert.match(script, /function renderDaemonLaunchBody\([\s\S]*wb-launch-primary/)
    assert.match(script, /function summarizeIntentSuggestion\(text\)/)
    assert.match(script, /function hydrateDaemonLaunchContext\(item\)/)
    assert.match(script, /function renderHelpButton\(id, label, content\)/)
    assert.match(script, /wb-intent-input-shell[\s\S]*wb-intent-recommendation/)
    assert.match(script, /title="完整建议：\$\{escAttr\(primarySuggestion\)\}"/)
    assert.match(script, /summarizeIntentSuggestion\(text\)/)
    assert.match(script, /data-intent-toggle aria-expanded="false" aria-controls="wbIntentSuggestions">更多建议/)
    assert.match(script, /additionalSuggestions = intentContext\.suggestions\.slice\(1\)/)
    assert.match(script, /wb-launch-context[\s\S]*wbDaemonSlug/)
    assert.match(script, /正在从 Daemon 同步默认上下文/)
    assert.match(script, /已同步 Daemon 默认上下文；你仍可手动覆盖/)
    assert.match(script, /PRD \/ asset 文件/)
    assert.match(script, /PRD\.md 或 assets\/mockup\.png/)
    assert.match(script, /function renderDaemonLaunchBody\([\s\S]*wb-launch-advanced/)
    assert.match(script, /wb-launch-advanced[\s\S]*wb-launch-extra-grid/)
    assert.match(script, /suggestions\.hidden = !expanded/)
    assert.match(script, /toggle\.textContent = expanded \? '收起建议' : '更多建议'/)
    assert.match(script, /data-help-toggle aria-expanded="false"/)
    assert.match(script, /data-help-popover role="tooltip"/)
    assert.match(script, /help\.hidden = !expanded/)
    assert.match(html, /\.wb-launch-advanced\s*\{[^}]*background:#fafaf9/s)
    assert.match(html, /\.wb-launch-primary\s*\{[^}]*box-shadow/s)
    assert.match(html, /\.wb-intent-recommendation\s*\{[^}]*border:1px solid/s)
    assert.match(html, /\.wb-intent-toggle\s*\{[^}]*border:1px solid/s)
    assert.match(html, /\.wb-launch-extra-grid\s*\{[^}]*grid-template-columns:repeat\(3/s)
    assert.match(html, /\.wb-launch-advanced\[open\]\s*> summary::before/)
    assert.match(html, /\.wb-help-trigger\s*\{[^}]*border:1px solid/s)
    assert.match(html, /\.wb-help-popover\s*\{[^}]*position:absolute/s)
    assert.match(preload, /workbenchDaemonLaunchContext:/)
  })

  it('keeps DAG internals out of the workflow catalog cards', () => {
    assert.match(script, /function workflowCatalogSummary\(workflow\)/)
    assert.match(script, /workflowCatalogSummary\(w\)/)
    assert.match(script, /选择后查看流程说明与执行拓扑/)
    assert.match(script, /summary: item\.summary/)
  })

  it('uses a low-cognitive-load home instead of a dashboard wall', () => {
    assert.doesNotMatch(html, /wb-overview-stats/)
    assert.doesNotMatch(html, /Command center/i)
    assert.match(html, /选择工作流/)
    assert.match(html, /先选工作流，再查看关系图并启动/)
    assert.match(html, /专家团队，按需加入/)
  })

  it('uses a wide desktop canvas with a persistent today todo', () => {
    assert.match(html, /\.wb-dashboard\s*\{[^}]*width:min\(1440px, 100%\)[^}]*grid-template-columns:repeat\(12/s)
    assert.match(html, /id="wbTodoPanel"/)
    assert.match(html, /id="wbTodoForm"/)
    assert.match(html, /id="wbTodoList"/)
    assert.match(html, /今日待办/)
    assert.match(script, /async function loadTodos\(\)/)
    assert.match(script, /async function addTodo\(text\)/)
    assert.match(script, /async function handleTodoAction\(id, action\)/)
    assert.match(html, /@media \(max-width: 760px\)[\s\S]*\.wb-start-panel\s*\{\s*order:2;\s*\}[\s\S]*\.wb-todo-panel\s*\{\s*order:4;\s*\}/)
  })

  it('persists today todos on disk instead of renderer cache', () => {
    const store = fs.readFileSync(path.join(__dirname, '..', 'src', 'lib', 'workbench-todo-store.js'), 'utf8')
    assert.match(store, /function createStore\(file\)/)
    assert.match(store, /clearDone/)
    assert.match(store, /importLegacy/)
    assert.match(main, /workbench-todos\.json/)
    assert.match(main, /ipcMain\.handle\('workbench-todo-list'/)
    assert.match(main, /ipcMain\.handle\('workbench-todo-add'/)
    assert.match(main, /ipcMain\.handle\('workbench-todo-clear-done'/)
    assert.match(preload, /workbenchTodoList:/)
    assert.match(preload, /workbenchTodoImportLegacy:/)
    // 旧的 localStorage 待办要迁移，不能静默丢
    assert.match(script, /TODO_STORAGE_KEY = 'knowme\.workbench\.todos\.v1'/)
    assert.match(script, /api\.workbenchTodoImportLegacy\(legacy\)/)
    assert.match(script, /localStorage\.removeItem\(TODO_STORAGE_KEY\)/)
    assert.doesNotMatch(script, /localStorage\.setItem\(TODO_STORAGE_KEY/)
    // 已完成项要有出口，否则列表只会越积越长
    assert.match(html, /id="wbTodoClear"/)
    assert.match(script, /async function clearDoneTodos\(\)/)
    assert.match(script, /今天都完成了/)
  })

  it('keeps recent task cards user-facing instead of exposing internal slugs', () => {
    assert.match(script, /function workbenchTaskMeta\(task = \{\}\)/)
    assert.match(script, /function workbenchTaskStateLabel\(state\)/)
    assert.match(script, /<span class="wb-task-intent">\$\{esc\(meta\)\}<\/span>/)
    assert.match(script, /<span class="wb-task-state">\$\{esc\(stateLabel\)\}<\/span>/)
    assert.doesNotMatch(script, /<span class="wb-task-intent">\$\{esc\(task\.slug\)\}<\/span>/)
  })

  it('renders workflows returned by workbench-load', () => {
    assert.match(script, /workflows:\s*Array\.isArray\(res\.workflows\)/)
    assert.match(script, /function renderWorkflows\(\)/)
    assert.match(script, /class="wb-workflow-card"/)
    assert.match(script, /当前仓库没有可预览的流程模板/)
    assert.match(script, /暂无可用工作流/)
  })

  it('binds templates to daemon execution with repository fallback', () => {
    assert.match(main, /workbenchRepo\.resolveActiveRepo\(loadSourcesStore\(\)\)/)
    assert.match(main, /workbenchRepo\.resolveWorkflowFile\(repo\.root,\s*rel\)/)
    assert.match(main, /workbenchDaemon\.createClient\(\{\s*endpoint,\s*token\s*\}\)/)
    assert.match(main, /workbenchAuth\.resolveToken\(settings\)/)
    assert.match(workspace, /workbenchOn && window\.Workbench\) window\.Workbench\.load\(\)/)
    assert.match(html, /id="wbRunner"/)
    assert.match(html, /id="wbWorkflowModal"/)
    assert.match(html, /开始任务/)
    assert.match(script, /window\.api\.workbenchDaemonStart/)
    assert.match(script, /window\.api\.workbenchDaemonTask/)
    assert.match(script, /已打开本地工作流/)
    assert.match(script, /window\.api\.workbenchWorkflow\(merged\)/)
    assert.match(script, /handleDaemonAuthFailure/)
    assert.match(script, /openWorkbenchAuthHelp/)
    assert.match(script, /function confirmModal\(\)/)
  })

  it('exposes semantic daemon IPC without an arbitrary request bridge', () => {
    assert.match(preload, /workbenchDaemonStart/)
    assert.match(preload, /workbenchDaemonTask/)
    assert.match(preload, /workbenchDaemonGate/)
    assert.match(preload, /workbenchDaemonClarify/)
    assert.match(preload, /workbenchAuthStatus/)
    assert.match(preload, /workbenchAuthLogin/)
    assert.match(preload, /workbenchAuthLogout/)
    assert.match(preload, /workbenchDaemonOverview/)
    assert.match(preload, /onWorkbenchAuthChanged/)
    assert.match(preload, /workbench-auth-changed/)
    assert.doesNotMatch(preload, /workbenchDaemonRequest/)
    assert.match(main, /ipcMain\.handle\('workbench-auth-status'/)
    assert.match(main, /ipcMain\.handle\('workbench-auth-login'/)
    assert.match(main, /ipcMain\.handle\('workbench-auth-logout'/)
    assert.match(main, /ipcMain\.handle\('workbench-daemon-overview'/)
    assert.match(main, /notifyWorkbenchAuthChanged/)
    assert.match(main, /workbench-auth-changed/)
    assert.match(script, /onWorkbenchAuthChanged/)
    assert.match(script, /handleWorkbenchAuthChanged/)
    assert.match(script, /workbenchDaemonOverview/)
  })

  it('adds an automation tab with dedicated IPC surface', () => {
    assert.doesNotMatch(html, /id="wbTabAutomation"/)
    assert.match(html, /id="wbAutomationPage"/)
    assert.match(html, /id="wbAutomationList"/)
    assert.match(html, /id="wbAutomationTemplates"/)
    assert.match(html, /id="wbAutomationModal"/)
    assert.match(html, /id="wbAutomationModalBody"/)
    assert.match(html, /id="wbAutomationModalSave"/)
    assert.match(script, /function renderAutomation\(\)/)
    assert.match(script, /function openAutomationModal\(/)
    assert.match(script, /function saveAutomationModal\(/)
    assert.match(script, /workbenchAutomationCreate/)
    assert.match(script, /workbenchAutomationUpdate/)
    assert.match(script, /workbenchAutomationDelete/)
    assert.match(script, /workbenchAutomationList/)
    assert.match(main, /ipcMain\.handle\('workbench-automation-list'/)
    assert.match(main, /ipcMain\.handle\('workbench-automation-run-now'/)
    assert.match(main, /ipcMain\.handle\('workbench-automation-delete'/)
    assert.match(preload, /workbenchAutomationList/)
    assert.match(preload, /workbenchAutomationRunNow/)
    assert.match(preload, /workbenchAutomationFeishuTargets/)
    assert.match(preload, /workbenchAutomationCreate/)
    assert.match(preload, /workbenchAutomationUpdate/)
    assert.match(preload, /workbenchAutomationDelete/)
  })

  it('shows automation as an independent surface mode', () => {
    assert.match(html, /\.app\.mode-agent\.mode-automation:not\(\.agent-has-document\) #workSurfaceWrap \{ display:flex; \}/)
    assert.match(html, /\.app\.mode-automation #workSurfaceWrap \.workbench \{ display:flex;/)
    assert.match(html, /\.app\.mode-automation \.wb-tabs \{ display:none !important; \}/)
    assert.match(html, /\.app\.mode-automation #wbAutomationPage \{ display:block !important; \}/)
    assert.match(workspace, /shell\.classList\.toggle\('mode-automation', inAutomation\)/)
    assert.match(workspace, /function openWorkbenchHome\(\)/)
  })

  it('uses the whole automation template card as an accessible create action', () => {
    assert.match(script, /function automationTemplateIcon\(templateId\)/)
    assert.match(script, /<button type="button" class="wb-automation-template" data-auto-template-action="create"/)
    assert.match(script, /wb-automation-template-icon/)
    assert.match(script, /data-icon="\$\{automationTemplateIcon\(template\.id\)\}"/)
    assert.match(script, /\|\| 'automation'/)
    assert.doesNotMatch(script, />使用模板<\/button>/)
    assert.match(html, /\.wb-automation-template:focus-visible\s*\{/)
    assert.match(html, /\.wb-automation-template:hover\s*\{/)
  })
})
