import '@testing-library/jest-dom/vitest'
import { render, screen, waitFor } from '@testing-library/react'
import { expect } from 'vitest'
import type { ReactElement } from 'react'
import type { KnowMeApi } from '../../shared/api'
import type { RunState } from '../app/store-types'
import { useAppStore } from '../app/store'

/** 渲染壳并等到懒表面 pending 消失。Vitest 下表面同步解析，通常立即通过。 */
export async function renderApp(ui: ReactElement) {
  const view = render(ui)
  await waitFor(() => {
    expect(screen.queryByTestId('km-surface-pending')).not.toBeInTheDocument()
  }, { timeout: 4000 })
  return view
}

export function makeRunState(overrides: Partial<RunState> & Pick<RunState, 'phase'>): RunState {
  return {
    taskId: overrides.taskId ?? '',
    workflowId: 'wf-1',
    workflowName: '会议闭环',
    slug: 'wf-1',
    lane: 'workflow',
    brief: '',
    log: [],
    gateNode: null,
    clarifyNode: null,
    gateTitle: null,
    processLogsText: '',
    progressText: '',
    showProcess: false,
    artifacts: [],
    inputAgents: [],
    agents: [],
    graphNodes: [],
    currentOwner: '',
    projectionDegraded: false,
    projectionDegradedReason: '',
    reviewTab: 'steps',
    reviewEvents: [],
    reviewChanges: { summary: '', files: [], empty: true },
    daemonStatus: '',
    dialogueMessages: [],
    ...overrides,
    launchInputs: overrides.launchInputs ?? {},
    workflowRunId: overrides.workflowRunId ?? '',
    workflowPackage: overrides.workflowPackage ?? null,
    selectedNodeId: overrides.selectedNodeId ?? null,
  }
}

export function resetAppStore() {
  useAppStore.setState({
    route: 'assistant',
    settingsTab: 'sources',
    workbenchSurface: 'taskhome',
    filesOpen: false,
    shelfQuery: '',
    shelfDomain: 'all',
    shelfLayout: 'grid',
    shelfCards: [],
    shelfLoading: false,
    shelfDaemonOnline: null,
    daemonOverviewCache: null,
    tasks: [],
    run: null,
    expertRoom: null,
    workbenchDialogue: { composer: '', attachments: [] },
    managePanel: 'daemon',
    sessions: [{ id: 's1', title: '新助手', agentId: 'general' }],
    sessionHistory: [],
    activeSessionId: 's1',
    sessionStates: { s1: { messages: [], composer: '', attachments: [] } },
    fileCatalog: [],
    isGenerating: false,
    assistantModels: [],
    assistantModelGroups: [],
    assistantModelId: '',
    assistantSkills: [],
    assistantStatus: '',
    assistantProcessFeed: '',
    assistantContextInfo: null,
    assistantProcessLines: [],
    assistantCancelStage: '',
    assistantRecovery: null,
    imageViewerUrl: '',
    generateRunId: '',
    fileTreeQuery: '',
    sources: [],
    activeSourceId: null,
    fileTreeNodes: [],
    fileTreeTruncated: false,
    fileTreeLoading: false,
    fileTreeCollapsed: {},
    assistantApplyTarget: null,
    knowledgePage: 'status',
    knowledgeQuery: '',
    knowledgeFilter: 'all',
    knowledgeWiki: [],
    knowledgeOkf: [],
    knowledgeWikiRoot: '',
    knowledgeHits: [],
    knowledgeLoading: false,
    knowledgeSearching: false,
    knowledgeMessage: null,
    knowledgeReader: null,
    knowledgeSelectedPath: null,
    knowledgeCollapsedDirs: {},
    knowledgeCollapsedSeeded: false,
    knowledgeLintIssues: [],
    knowledgeLinting: false,
    knowledgeOrganizing: false,
    knowledgeProviders: [],
    knowledgeActiveProviderId: null,
    knowledgeMoreOpen: false,
    knowledgeSelectedProposalId: null,
    stewardProposals: [],
    hubTab: 'expert',
    hubQuery: '',
    hubItems: [],
    hubLoading: false,
    studioDraft: null,
    studioIssues: [],
    studioSaving: false,
    studioReturnSurface: null,
    studioReturnManagePanel: null,
    studioKnowledgeProviders: [],
    modes: [],
    activeModeId: '',
    automationJobs: [],
    automationTemplates: [],
    manageLoading: false,
    overlayToast: '',
    overlayDrawer: null,
    overlayContextMenu: null,
    confirmModal: null,
    workspaceModal: null,
    taskManageOpen: false,
    attentionItems: [],
    attentionPulse: false,
    fabricStats: null,
    stewardTasks: [],
    knowledgeIoLoading: false,
    linkPreview: null,
    linkFullscreen: false,
    linkTitleCache: {},
  })
}

export { useAppStore }

export function mockApi(partial: Partial<KnowMeApi> = {}): KnowMeApi {
  const api = {
    workbenchLoad: async () => ({ workflows: [], workflowPackages: [] }),
    workbenchModeList: async () => ({ ok: true, modes: [], activeModeId: '' }),
    workbenchModeSelect: async (modeId: string) => ({ ok: true, activeModeId: modeId, modes: [] }),
    workbenchAutomationList: async () => ({ ok: true, jobs: [], templates: [] }),
    workbenchWorkflowPackageSave: async () => ({ ok: true, package: { id: 'my-test', graph: {} } }),
    workbenchTaskList: async () => ({ items: [] }),
    workbenchTaskCreate: async () => ({}),
    workbenchTaskUpdate: async () => ({}),
    workbenchTaskGet: async () => null,
    workbenchTaskArchive: async () => ({ ok: true }),
    workbenchWorkflowPackageList: async () => ({ items: [] }),
    workbenchWorkflowPackageGet: async () => ({ ok: true, package: { graph: { nodes: [{ kind: 'agent', name: '制作人' }] } } }),
    workbenchWorkflowPackageFork: async () => ({ ok: true, package: { id: 'my-fork-copy', graph: {} } }),
    workbenchWorkflowPackageArchive: async () => ({ ok: true }),
    workbenchDaemonTask: async () => ({
      ok: true,
      projection: {
        agents: ['制作人', '开发'],
        graphNodes: [{ id: 'n1', label: '整理纪要', meta: 'agent · 制作人', status: 'active' }],
        currentOwner: '制作人',
      },
    }),
    workbenchDaemonOverview: async () => ({}),
    workbenchDaemonProgress: async () => ({ ok: true, text: 'step 1/3' }),
    workbenchDaemonEvents: async () => ({ ok: true, events: [{ id: 'e1', type: 'step', message: 'started' }] }),
    workbenchDaemonChanges: async () => ({ ok: true, files: [{ path: 'out.md', status: 'added' }] }),
    workbenchDaemonGate: async () => ({}),
    workbenchDaemonClarify: async () => ({ ok: true }),
    workbenchDaemonCancel: async () => ({}),
    workbenchLaunchStart: async () => ({}),
    workbenchPickFiles: async () => ({ ok: true, canceled: true, files: [] }),
    workbenchDaemonLogs: async () => ({}),
    workbenchDaemonArtifacts: async () => ({ items: [] }),
    workbenchAutomationCreate: async () => ({ ok: true }),
    workbenchAutomationUpdate: async () => ({ ok: true }),
    workbenchAutomationDelete: async () => ({ ok: true }),
    workbenchAutomationRunNow: async () => ({ ok: true }),
    appInfo: async () => ({ name: 'KnowMe', version: '0.3.0' }),
    getSettings: () => ({}),
    openSettings: () => undefined,
    openSettingsWindow: () => undefined,
    onWorkspaceOpenSettings: () => () => undefined,
    llmProfile: async () => ({}),
    llmModels: async () => ({ presets: [] }),
    llmSetModel: async () => ({ ok: true }),
    llmProbe: async () => ({ ok: true, latencyMs: 12, host: 'example.com', model: 'qwen-turbo' }),
    agentSessionList: async () => ({ items: [] }),
    agentSessionNew: async () => ({ id: 'n1', title: '新对话' }),
    agentSessionGet: async () => null,
    agentSessionRename: async () => ({ ok: true }),
    agentSessionPin: async () => ({ ok: true }),
    agentSessionFork: async () => ({ id: 'f1', title: '分叉' }),
    agentSessionCloseTab: async () => ({ ok: true }),
    agentSessionSetUi: async () => ({ ok: true }),
    agentSessionContextUpdate: async () => ({ ok: true }),
    copyToClipboard: () => undefined,
    openLogsWindow: () => undefined,
    aiGenerate: async () => ({ text: '你好，我是知我。需要我帮你做什么？' }),
    aiCancelRun: async () => ({}),
    onAiStreamChunk: () => () => undefined,
    onAiStreamEvent: () => () => undefined,
    knowledgeProviderList: async () => ({ ok: true, providers: [{ id: 'local-default', displayName: '本地知识库' }] }),
    knowledgeOsList: async () => ({ ok: true, wiki: [], okf: [] }),
    knowledgeOsRead: async () => ({ ok: false, error: 'not found' }),
    knowledgeOsLint: async () => ({ ok: true, issues: [] }),
    knowledgeOsRefresh: async () => ({ ok: true, scanned: 0 }),
    knowledgeAddMaterial: async () => ({ ok: true }),
    knowledgeStewardTaskList: async () => ({ ok: true, tasks: [], proposals: [] }),
    knowledgeStewardTaskCreate: async () => ({ ok: true, task: { id: 'st1' } }),
    knowledgeStewardProposalAccept: async () => ({ ok: true }),
    knowledgeStewardProposalReject: async () => ({ ok: true }),
    knowledgeStewardProposalSnooze: async () => ({ ok: true }),
    memoryOverview: async () => ({ patterns: [], recent: [], stats: {} }),
    memoryReviewPattern: async () => ({ ok: true }),
    capabilityPackList: async () => ({ ok: true, items: [] }),
    capabilityPackEmptyState: async () => ({ ok: true, groups: [] }),
    capabilityList: async () => ({ ok: true, items: [] }),
    capabilityImport: async () => ({ ok: true }),
    capabilityImportPrecheck: async () => ({
      ok: true,
      preview: {
        name: '预检能力',
        kind: 'skill',
        risk: { level: 'low', reasons: [] },
        compatibility: { status: 'compatible' },
        rollbackHint: '安装后可停用',
      },
    }),
    capabilityScanCursorRepository: async () => ({ ok: true, previewToken: 'tok', name: 'repo' }),
    capabilityPickLocalFolder: async () => ({ ok: true, path: 'D:/cap' }),
    capabilityPickZipFile: async () => ({ ok: true, path: 'D:/cap.zip' }),
    capabilityPickCursorRepository: async () => ({ ok: true, path: 'D:/cursor-repo' }),
    capabilityImportCursorRepository: async () => ({ ok: true }),
    capabilityEnable: async () => ({ ok: true }),
    capabilityDisable: async () => ({ ok: true }),
    capabilityInstall: async () => ({ ok: true }),
    expertGet: async () => ({ ok: true, expert: null }),
    expertSave: async () => ({ ok: true }),
    expertDelete: async () => ({ ok: true }),
    knowledgeExport: async () => ({ ok: true }),
    knowledgeImport: async () => ({ ok: true }),
    connectorsList: async () => ({ items: [] }),
    connectorsStatus: async () => ({ ok: false, message: '未连接' }),
    connectorsFeishuAuthStart: async () => ({ ok: false, message: '未配置' }),
    knowledgeSearch: async () => ({ ok: true, hits: [] }),
    sourcesList: async () => ({ sources: [], activeSourceId: null }),
    sourcesTree: async () => ({ ok: true, nodes: [] }),
    sourcesTreeChildren: async () => ({ ok: true, nodes: [] }),
    sourcesSetActive: async () => ({ ok: true }),
    sourcesReadFile: async () => ({ ok: true, content: '' }),
    sourcesWriteFile: async () => ({ ok: true }),
    sourcesOpenRoot: async () => ({ ok: true }),
    agentArtifactAdd: async () => ({ ok: true }),
    agentArtifactAccept: async () => ({ ok: true }),
    agentArtifactReject: async () => ({ ok: true }),
    agentApplyLog: async () => ({ ok: true }),
    ...partial,
  } as KnowMeApi
  window.api = api
  return api
}
