const { ipcRenderer } = require("electron")

module.exports = {
  copyToClipboard: text => ipcRenderer.send('copy-to-clipboard', text),

  // AI
  aiGenerate: p => ipcRenderer.invoke('ai-generate', p),
  aiCancelRun: runId => ipcRenderer.invoke('ai-cancel-run', String(runId || '')),
  agentRunTree: rootRunId => ipcRenderer.invoke('agent-run-tree', { rootRunId: String(rootRunId || '') }),
  agentRunStatus: runId => ipcRenderer.invoke('agent-run-status', { runId: String(runId || '') }),
  agentRunCancel: runId => ipcRenderer.invoke('agent-run-cancel', { runId: String(runId || '') }),
  agentRunRetry: (runId, opts) => ipcRenderer.invoke('agent-run-retry', { runId: String(runId || ''), ...(opts || {}) }),
  agentRunResume: (runId, action) => ipcRenderer.invoke('agent-run-resume', { runId: String(runId || ''), action: String(action || 'continue') }),
  workbenchAgentGraphPlan: payload => ipcRenderer.invoke('workbench-agent-graph-plan', payload || {}),
  workbenchAgentGraphValidate: payload => ipcRenderer.invoke('workbench-agent-graph-validate', payload || {}),
  workbenchAgentGraphStart: payload => ipcRenderer.invoke('workbench-agent-graph-start', payload || {}),
  workbenchAgentRunTree: rootRunId => ipcRenderer.invoke('workbench-agent-run-tree', { rootRunId: String(rootRunId || '') }),
  workbenchAgentRunDecision: payload => ipcRenderer.invoke('workbench-agent-run-decision', payload || {}),
  llmProfile: () => ipcRenderer.invoke('llm-profile'),
  llmModels: () => ipcRenderer.invoke('llm-models'),
  llmSetModel: p => ipcRenderer.invoke('llm-set-model', p),
  agentSessionList: () => ipcRenderer.invoke('agent-session-list'),
  agentSessionGet: id => ipcRenderer.invoke('agent-session-get', id),
  agentSessionNew: agentIdOrOpts => ipcRenderer.invoke('agent-session-new', agentIdOrOpts),
  agentSessionContextUpdate: (sessionId, patch) =>
    ipcRenderer.invoke('agent-session-context-update', sessionId, patch || {}),
  agentSessionSetUi: patch => ipcRenderer.invoke('agent-session-set-ui', patch),
  agentSessionRename: (id, title) => ipcRenderer.invoke('agent-session-rename', id, title),
  agentSessionFork: id => ipcRenderer.invoke('agent-session-fork', id),
  agentSessionSummary: id => ipcRenderer.invoke('agent-session-summary', id),
  agentSessionTranscript: id => ipcRenderer.invoke('agent-session-transcript', id),
  agentSessionPin: (id, pinned) => ipcRenderer.invoke('agent-session-pin', id, pinned),
  agentSessionCloseTab: id => ipcRenderer.invoke('agent-session-close-tab', id),
  agentRunUpdate: payload => ipcRenderer.invoke('agent-run-update', payload || {}),
  agentArtifactAdd: payload => ipcRenderer.invoke('agent-artifact-add', payload || {}),
  agentArtifactAccept: payload => ipcRenderer.invoke('agent-artifact-accept', payload || {}),
  agentArtifactReject: payload => ipcRenderer.invoke('agent-artifact-reject', payload || {}),
  agentApplyLog: payload => ipcRenderer.invoke('agent-apply-log', payload || {}),
  knowledgeOsList: () => ipcRenderer.invoke('knowledge-os-list'),
  knowledgeOsRefresh: () => ipcRenderer.invoke('knowledge-os-refresh'),
  obsidianStatus: () => ipcRenderer.invoke('obsidian-status'),
  obsidianInstall: () => ipcRenderer.invoke('obsidian-install'),
  obsidianBridgeInstall: () => ipcRenderer.invoke('obsidian-bridge-install'),
  obsidianOpen: () => ipcRenderer.invoke('obsidian-open'),
  // 用户任务接口；下方 knowledgeOs* 保留为兼容别名。
  knowledgeSearch: q => ipcRenderer.invoke('knowledge-os-query', q),
  knowledgeAddMaterial: payload => ipcRenderer.invoke('knowledge-os-ingest', payload || {}),
  knowledgeCheck: () => ipcRenderer.invoke('knowledge-os-lint'),
  knowledgeOsQuery: q => ipcRenderer.invoke('knowledge-os-query', q),
  knowledgeOsIngest: payload => ipcRenderer.invoke('knowledge-os-ingest', payload || {}),
  knowledgeOsLint: () => ipcRenderer.invoke('knowledge-os-lint'),
  knowledgeOsPromote: payload => ipcRenderer.invoke('knowledge-os-promote', payload || {}),
  knowledgeOsRead: payload => ipcRenderer.invoke('knowledge-os-read', payload || {}),
  knowledgeOsHarnessStatus: () => ipcRenderer.invoke('knowledge-os-harness-status'),
  knowledgeOsSaveRaw: payload => ipcRenderer.invoke('knowledge-os-save-raw', payload || {}),
  knowledgeOsConfig: patch => ipcRenderer.invoke('knowledge-os-config', patch),
  knowledgeOsStewardLint: sessionId => ipcRenderer.invoke('knowledge-os-steward-lint', sessionId),
  knowledgeStewardTaskList: () => ipcRenderer.invoke('knowledge-steward-task-list'),
  knowledgeStewardTaskCreate: payload => ipcRenderer.invoke('knowledge-steward-task-create', payload || {}),
  knowledgeStewardTaskCancel: id => ipcRenderer.invoke('knowledge-steward-task-cancel', id),
  knowledgeStewardTaskRetry: id => ipcRenderer.invoke('knowledge-steward-task-retry', id),
  knowledgeStewardProposalAccept: payload => ipcRenderer.invoke('knowledge-steward-proposal-accept', payload),
  knowledgeStewardProposalReject: id => ipcRenderer.invoke('knowledge-steward-proposal-reject', id),
  knowledgeStewardProposalSnooze: id => ipcRenderer.invoke('knowledge-steward-proposal-snooze', id),
  // 知识库 Provider：本地 / 远程 RAG
  knowledgeProviderList: () => ipcRenderer.invoke('knowledge-provider-list'),
  knowledgeProviderSave: payload => ipcRenderer.invoke('knowledge-provider-save', payload || {}),
  knowledgeProviderRemove: id => ipcRenderer.invoke('knowledge-provider-remove', id),
  knowledgeProviderSetActive: id => ipcRenderer.invoke('knowledge-provider-set-active', id),
  knowledgeProviderQuery: q => ipcRenderer.invoke('knowledge-provider-query', q),
  fabricGraph: () => ipcRenderer.invoke('fabric-graph'),
  fabricQuery: q => ipcRenderer.invoke('fabric-query', q),
  fabricKbQuery: payload => ipcRenderer.invoke('fabric-kb-query', payload || {}),
  fabricKbGet: ref => ipcRenderer.invoke('fabric-kb-get', ref),
  fabricWeaveList: () => ipcRenderer.invoke('fabric-weave-list'),
  fabricWeaveRun: payload => ipcRenderer.invoke('fabric-weave-run', payload || {}),
  fabricWeaveApply: id => ipcRenderer.invoke('fabric-weave-apply', id),
  fabricWeaveReject: id => ipcRenderer.invoke('fabric-weave-reject', id),
  fabricEngineStatus: () => ipcRenderer.invoke('fabric-engine-status'),
  fabricGovernanceCheckup: () => ipcRenderer.invoke('fabric-governance-checkup'),
  fabricGovernanceProposals: () => ipcRenderer.invoke('fabric-governance-proposals'),
  fabricGovernanceProposalApply: id => ipcRenderer.invoke('fabric-governance-proposal-apply', id),
  fabricGovernanceProposalReject: id => ipcRenderer.invoke('fabric-governance-proposal-reject', id),
  fabricGovernanceAction: payload => ipcRenderer.invoke('fabric-governance-action', payload || {}),
  fabricReweaveRun: payload => ipcRenderer.invoke('fabric-reweave-run', payload || {}),
  fabricGovernanceConfig: patch => ipcRenderer.invoke('fabric-governance-config', patch),
  kbMount: payload => ipcRenderer.invoke('kb-mount', payload || {}),
  knowledgeExport: opts => ipcRenderer.invoke('knowledge-export', opts || {}),
  knowledgeImport: () => ipcRenderer.invoke('knowledge-import'),
  connectorsList: () => ipcRenderer.invoke('connectors-list'),
  connectorsStatus: id => ipcRenderer.invoke('connectors-status', id),
  connectorsFeishuAuthStart: options =>
    ipcRenderer.invoke('connectors-feishu-auth-start', {
      force: Boolean(options?.force),
      full: Boolean(options?.full),
      scopes: Array.isArray(options?.scopes) ? options.scopes : [],
    }),
  connectorsUpsert: patch => ipcRenderer.invoke('connectors-upsert', patch || {}),
  connectorsSetAllowlist: (id, allowlist) =>
    ipcRenderer.invoke('connectors-set-allowlist', id, allowlist),
  connectorsCreateDocDraft: payload =>
    ipcRenderer.invoke('connectors-create-doc-draft', payload || {}),
  toolDraftsList: () => ipcRenderer.invoke('tool-drafts-list'),
  toolApproveDraft: payload => ipcRenderer.invoke('tool-approve-draft', payload || {}),
  toolRollbackDraft: payload => ipcRenderer.invoke('tool-rollback-draft', payload || {}),

  // Workbench：AgentTeams 编排入口
  workbenchLoad: () => ipcRenderer.invoke('workbench-load'),
  workbenchWorkflow: payload => ipcRenderer.invoke('workbench-workflow', payload || {}),
  workbenchDispatch: payload => ipcRenderer.invoke('workbench-dispatch', payload || {}),
  workbenchDaemonStart: payload => ipcRenderer.invoke('workbench-daemon-start', payload || {}),
  workbenchDaemonTask: slug => ipcRenderer.invoke('workbench-daemon-task', slug),
  workbenchDaemonArtifacts: slug => ipcRenderer.invoke('workbench-daemon-artifacts', slug),
  workbenchDaemonProgress: slug => ipcRenderer.invoke('workbench-daemon-progress', slug),
  workbenchDaemonLogs: slug => ipcRenderer.invoke('workbench-daemon-logs', slug),
  workbenchDaemonLogsStreamStart: payload => ipcRenderer.invoke('workbench-daemon-logs-stream-start', payload || {}),
  workbenchDaemonLogsStreamStop: payload => ipcRenderer.invoke('workbench-daemon-logs-stream-stop', payload || {}),
  onWorkbenchDaemonLogEvent: cb => {
    const fn = (_e, event) => cb(event)
    ipcRenderer.on('workbench-daemon-log-event', fn)
    return () => ipcRenderer.removeListener('workbench-daemon-log-event', fn)
  },
  workbenchDaemonEvents: (slug, query) => ipcRenderer.invoke('workbench-daemon-events', slug, query || {}),
  workbenchDaemonChanges: slug => ipcRenderer.invoke('workbench-daemon-changes', slug),
  workbenchDaemonWorkspaceTree: (slug, relPath) => ipcRenderer.invoke('workbench-daemon-workspace-tree', slug, relPath || ''),
  workbenchDaemonWorkspaceBlob: (slug, relPath) => ipcRenderer.invoke('workbench-daemon-workspace-blob', slug, relPath || ''),
  workbenchDaemonLaunchContext: workflowId => ipcRenderer.invoke('workbench-daemon-launch-context', workflowId),
  workbenchPickFiles: payload => ipcRenderer.invoke('workbench-pick-files', payload || {}),
  workbenchDaemonArtifactOpen: payload => ipcRenderer.invoke(
    'workbench-daemon-artifact-open',
    typeof payload === 'string' ? { path: payload } : (payload || {}),
  ),
  workbenchDaemonGate: (slug, payload) => ipcRenderer.invoke('workbench-daemon-gate', slug, payload || {}),
  workbenchDaemonClarify: (slug, payload) => ipcRenderer.invoke('workbench-daemon-clarify', slug, payload || {}),
  workbenchDaemonCancel: (slug, payload) => ipcRenderer.invoke('workbench-daemon-cancel', slug, payload || {}),
  workbenchAuthStatus: () => ipcRenderer.invoke('workbench-auth-status'),
  workbenchAuthLogin: payload => ipcRenderer.invoke('workbench-auth-login', payload || {}),
  workbenchAuthLogout: () => ipcRenderer.invoke('workbench-auth-logout'),
  workbenchBootstrapStatus: () => ipcRenderer.invoke('workbench-bootstrap-status'),
  workbenchBootstrapRun: payload => ipcRenderer.invoke('workbench-bootstrap-run', payload || {}),
  workbenchDaemonOverview: () => ipcRenderer.invoke('workbench-daemon-overview'),
  gameStudioScenes: () => ipcRenderer.invoke('game-studio-scenes'),
  capabilityPackList: () => ipcRenderer.invoke('capability-pack-list'),
  capabilityPackEmptyState: () => ipcRenderer.invoke('capability-pack-empty-state'),
  capabilityPackInstall: payload => ipcRenderer.invoke('capability-pack-install', payload || {}),
  capabilityPackEnable: payload => ipcRenderer.invoke('capability-pack-enable', payload || {}),
  capabilityPackDisable: payload => ipcRenderer.invoke('capability-pack-disable', payload || {}),
  capabilityPackUninstall: payload => ipcRenderer.invoke('capability-pack-uninstall', payload || {}),
  gameRequirementBuild: payload => ipcRenderer.invoke('game-requirement-build', payload || {}),
  gameRequirementApprove: payload => ipcRenderer.invoke('game-requirement-approve', payload || {}),
  gameWorkbenchHandoff: payload => ipcRenderer.invoke('game-workbench-handoff', payload || {}),
  onWorkbenchAuthChanged: cb => {
    const fn = (_e, auth) => cb(auth)
    ipcRenderer.on('workbench-auth-changed', fn)
    return () => ipcRenderer.removeListener('workbench-auth-changed', fn)
  },
  workbenchTodoList: () => ipcRenderer.invoke('workbench-todo-list'),
  workbenchTodoAdd: text => ipcRenderer.invoke('workbench-todo-add', text),
  workbenchTodoToggle: id => ipcRenderer.invoke('workbench-todo-toggle', id),
  workbenchTodoRemove: id => ipcRenderer.invoke('workbench-todo-remove', id),
  workbenchTodoClearDone: () => ipcRenderer.invoke('workbench-todo-clear-done'),
  workbenchTodoImportLegacy: items => ipcRenderer.invoke('workbench-todo-import-legacy', items || []),
  workbenchTaskDraftGet: () => ipcRenderer.invoke('workbench-task-draft-get'),
  workbenchTaskDraftSave: patch => ipcRenderer.invoke('workbench-task-draft-save', patch || {}),
  workbenchTaskDraftClear: () => ipcRenderer.invoke('workbench-task-draft-clear'),
  workbenchTaskList: () => ipcRenderer.invoke('workbench-task-list'),
  workbenchTaskGet: id => ipcRenderer.invoke('workbench-task-get', id),
  workbenchTaskCreate: input => ipcRenderer.invoke('workbench-task-create', input || {}),
  workbenchTaskUpdate: (id, patch) => ipcRenderer.invoke('workbench-task-update', { id, patch: patch || {} }),
  workbenchTaskArchive: id => ipcRenderer.invoke('workbench-task-archive', id),
  onWorkbenchTaskScheduleDue: cb => {
    const fn = (_e, data) => cb(data)
    ipcRenderer.on('workbench-task-schedule-due', fn)
    return () => ipcRenderer.removeListener('workbench-task-schedule-due', fn)
  },
  workbenchWorkflowPackageList: filter => ipcRenderer.invoke('workbench-workflow-package-list', filter || {}),
  workbenchWorkflowPackageGet: id => ipcRenderer.invoke('workbench-workflow-package-get', id),
  workbenchWorkflowPackageSave: payload => ipcRenderer.invoke('workbench-workflow-package-save', payload || {}),
  workbenchWorkflowPackageFork: (id, options) => ipcRenderer.invoke('workbench-workflow-package-fork', id, options || {}),
  workbenchWorkflowPackageArchive: id => ipcRenderer.invoke('workbench-workflow-package-archive', id),
  agentProfileList: agentId => ipcRenderer.invoke('agent-profile-list', agentId || ''),
}
